== Export to Castle Animation Frames (castle-anim-frames)

To export _any_ kind of animation from Blender, use the exporter to our link:castle_animation_frames.php[Castle Animation Frames format]. The `.castle-anim-frames` files can be read by our engine and will play animations.

Internally they are a set of X3D or glTF files.

<div class="download jumbotron">
    <a class="btn btn-primary btn-lg" href="https://raw.githubusercontent.com/castle-engine/cge-blender/master/export_castle_anim_frames.py"><span class="glyphicon glyphicon-download" aria-hidden="true"></span><br>Download Castle Animation Frames exporter</a>
</div>

Install it like every other Blender addon:

1. Use the comfortable _File -> User Preferences (opens new window) -> Addons (tab) -> Install Addon... (button at the bottom)_. Or just copy the file directly to the `scripts/addons/` directory.
2. Enable it, by clicking the checkbox at _"Import-Export: Export Castle Animation Frames"_in the Addons window.

For Blender 2.82a: Apply link:https://github.com/KhronosGroup/glTF-Blender-IO/pull/991[this fix] if you're going to use glTF combined with castle-anim-frames (see below).

// <!-- Tested with _Blender >= 2.68_. -->

=== Actions and Frames

_Actions_ are Blender containers for animations. Each Blender object may have many actions, like _walk_, _run_, _die_... A new action is automatically created on an object (if needed) when you insert a keyframe.

In Blender, _it matters to which object you attach an action_. Action describes the complete animation of a given Blender object. If you try to reuse the same action on two different objects, you will find that they animate (move, rotate...) the same way. If you want every object to animate in a different way, _you will usually use an action only on a single object_. I explain this, to make it clear that _Blender actions do not span multiple objects_, which is a little different than what we need (we want to export a series of animations, and each animation should just apply to the whole scene).

When exporting the animation, you can select an object to _export all the actions of this object_. *If your scene includes an armature with some actions, we automatically select it as the object from which to take actions* (you can deselect it, if desired). The range of exported frames is determined by the minimum and maximum keyframe set in this action (that's how Blender calculates `action.frame_range` in Python).<!--  All other objects will animate according to their current actions, but this special object will have different action  -->

When you don't select any such object then we export the whole animation (from _Start_ to _End_ frames that you set on the _Timeline_). The resulting animation will be called just "`animation`" in this case (this is useful if you run animations from code, using the cgeref:TCastleSceneCore.PlayAnimation[TCastleScene.PlayAnimation] method). This is perfectly reasonable in many situations:

* if you don't have actions in your scene (if your animation is ruled only by physics), <!--, like _Rigid Body_ or _Cloth_ or _Particles</i-->
* or if you just want to export the current actions of all the objects,
* or if you configured the animation using Blender's NLA editor.

=== Exporting Various Animations Types to castle-anim-frames

Thanks to the simplicity of the `.castle-anim-frames` format,
*this format exports every kind of Blender animation to our engine*:

* You can *transform* whole objects,
* You can animate using an *armature* (skeleton) attached to a skinned mesh or disjoint objects,
* You can *deform the mesh in any way (shape keys, hooks)*,
* You can use *fluid simulation*,
* You can use *physics* (rigid body, soft body, cloth; make sure to _play the complete animation in Blender right before exporting, to make it cached_),
* You can animate *material properties* (e.g. color or transparency),
* You can even animate *particles* (select the _"Make Duplicates Real (Export Particles)"_ checkbox)!

The `castle-anim-frames` animations render smoothly when the models are _"structurally equal"_, which means that you should only animate things that can be interpolated. <!-- (are expressed as floating-point values). --> You should not change a topology (e.g. create, destroy faces or whole objects) from one frame to another, at least _you should not change it too often_. In particular:

* You may want to avoid using Blender _"fluid simulation"_, as it always instantiates a different mesh topology every frame.
* Avoid having _"Triangulate"_ or _"Decimate"_ modifiers on a stack _after_ an animating modifier (like an _"Armature"_), as they will change the mesh topology differently every frame. Using these modifiers earlier on the stack is better.
* If you export particles, make sure that all the particles exist in every animation frame. It's easiest to achieve this by selecting to _Render_ both the _"Unborn"_ and _"Dead"_ particles.

Ignoring these advices will make the animation "jump" at certain frames, since the engine will not be able to interpolate between the frames you provided. Sometimes this is OK (e.g. when you really change one object to something completely different), but sometimes this is a bad artifact. Use the <?php echo a_href_page('view3dscene', 'view3dscene') ?> with `--debug-log` command-line option, and watch for warnings about the model not being _"structurally equal"_, if you want to eliminate such issues.

The `castle-anim-frames` exporter uses the X3D exporter (the original one, provided with Blender, or our custom one if installed) to export the static data. So if something doesn't look like you want after exporting, consult the advices above about using the X3D exporter. You can always export, as a test, a single frame of your animation to X3D, to check does it look OK.

TODO: Right now the interpolation is not done using the proper X3D interpolators at runtime, like `PositionInterpolator`. Instead we interpolate (create intermediate frames) at the load time, then put the resulting frames inside a `Switch` node, animated using the `IntegerSequencer`. The nodes inside all `Switch` nodes are shared smartly, but still the memory usage is much higher than it could be.

For the sake of the collision detection, each animation is treated as it's bounding box. Calculating detailed collision trees for every animation frame would be too time-consuming. TODO: We can improve it one day to collide as a _different_ bounding box, corresponding to the current animation frame, not to the whole animation.
