== TMS Smart Setup

Our engine can be also installed using https://github.com/tmssoftware/smartsetup[TMS Smart Setup] for Delphi.

This installs our packages in Delphi(s), with benefits being:

* more automatic (command-line to get and install),
* support for installing in multiple Delphi versions at the same time (as it automatically adds the suitable `libsuffix`, which our own packages don't do yet -- see below for details why).
* For more details see https://www.tmssoftware.com/site/blog.asp?post=1146[TMS blog post] and https://github.com/castle-engine/castle-engine/issues/678#issuecomment-3000913493[GH issue where we talk about it].

The drawback is that this doesn't install our tools (like https://castle-engine.io/editor[editor] or https://castle-engine.io/build_tool[build tool]). As such, it's not the advised way to install our engine right now for most users (better follow our https://castle-engine.io/delphi_packages[installation instructions for Delphi]).

However, it may be great to automated installation done by _continuous integration/delivery_, like in https://castle-engine.io/github_actions[GitHub Actions].

Short instructions how to do this:

. Get https://github.com/tmssoftware/smartsetup , with submodules, in branch `git-registry`. Command-line:
+
----
git clone https://github.com/tmssoftware/smartsetup
cd smartsetup
git checkout git-registry
git submodule update --init --recursive # get submodules in externals/
----

. Build and move the `.../bin/Win64/Debug/tms.exe` binary anywhere to `$PATH` on your system.
. Create and enter and directory to host the configuration, like `c:/smartsetup-test`. Enter it from the command-line and execute following commands inside it:
. `tms config` (it will open YAML file in your code editor; in principle you don't need to tweak it, the default config should work out-of-the-box)
. `tms server-enable community`
. `tms install castle.engine`
+
NOTE: Trouble? Try `tms install castle.engine -verbose`.
+
NOTE: If you're on Windows and you get `fatal: cannot create directory at ...: Filename too long` error then try doing `git config --global core.longpaths true`. See link:compiling_from_source.php[Compiling from source] for more info.
