#!/bin/bash
set -eu

# Script run by Jenkins (Automatic Cloud Builds of Castle Game Engine projects) on
# https://michalis.ii.uni.wroc.pl/jenkins/ to check compilation
# of various CGE programs.
# Parts of this script are really specific to the Jenkins
# and michalis.ii.uni.wroc.pl server configuration.

# castle-engine (used to compile some stuff) uses this,
# also some "cd" commands may use it.
export CASTLE_ENGINE_PATH=`pwd`/

# Do this first, for cleanup to work,
# this assumes we have castle-engine from previous compilation.
do_setup_bin ()
{
  CASTLE_BIN_PATH="${CASTLE_ENGINE_PATH}"snapshots-bin/
  mkdir -p "${CASTLE_BIN_PATH}"
  export PATH="${PATH}":"${CASTLE_BIN_PATH}"
}

# ----------------------------------------------------------------------------

do_clean ()
{
  echo '---------------------------------------------------------------'
  echo 'Cleaning everything'

  cd "${CASTLE_ENGINE_PATH}"
  scripts/clean_everything.sh
}

# ----------------------------------------------------------------------------

do_compile_tool ()
{
  echo '---------------------------------------------------------------'
  echo 'Compiling tools'

  cd "${CASTLE_ENGINE_PATH}"castle_game_engine/tools/build-tool/
  ./castle-engine_compile.sh
  mv -f castle-engine "${CASTLE_BIN_PATH}"

  cd "${CASTLE_ENGINE_PATH}"castle_game_engine/examples/tools/
  ./dircleaner_compile.sh
  mv -f dircleaner "${CASTLE_BIN_PATH}"

  cd "${CASTLE_ENGINE_PATH}"castle_game_engine/tools/image-to-pascal/
  ./image-to-pascal_compile.sh
  mv -f image-to-pascal "${CASTLE_BIN_PATH}"
}

# ----------------------------------------------------------------------------

do_compile_all_programs ()
{
  echo '---------------------------------------------------------------'
  echo 'Compiling all programs'

  cd "${CASTLE_ENGINE_PATH}"
  scripts/clean_everything.sh

  scripts/compile_all_programs.sh

  export CASTLE_FPC_OPTIONS=-Twin32
  export CASTLE_ENGINE_TOOL_OPTIONS=--os=win32
  scripts/compile_all_programs.sh
  export CASTLE_FPC_OPTIONS=''
  export CASTLE_ENGINE_TOOL_OPTIONS=''

  export CASTLE_FPC_OPTIONS='-Twin64 -Px86_64'
  export CASTLE_ENGINE_TOOL_OPTIONS='--os=win64 --cpu=x86_64'
  scripts/compile_all_programs.sh
  export CASTLE_FPC_OPTIONS=''
  export CASTLE_ENGINE_TOOL_OPTIONS=''
}

# main code ------------------------------------------------------------------

. /usr/local/fpclazarus/bin/setup.sh default
do_setup_bin
do_clean
do_compile_tool
do_clean
do_compile_all_programs

echo "----------- That's all folks :)"
