#!/bin/bash
set -eu

export CASTLE_ENGINE_PATH=/home/michalis/sources/castle-engine/trunk/

cd "$CASTLE_ENGINE_PATH"castle_game_engine/doc/pasdoc/
make clean
make html

OUTPUT_PATH="$HOME"/public_html/castle-engine-snapshots/docs/reference/
rm -Rf "$OUTPUT_PATH"
mkdir "$OUTPUT_PATH"
# mv latex/docs.pdf "$OUTPUT_PATH" # latex/pdf docs are not made, don't look good enough
mv html "$OUTPUT_PATH"
