#!/bin/bash
set -eu

# Call castle_engine_snapshot (see there for comments)
# with proper environment and capturing output

# log messages and dates in English
export LANG=C

export CASTLE_BINARY_PATH="${HOME}/bin/"

# Make sure you have dircleaner, fpc etc. on $PATH
export PATH="${CASTLE_BINARY_PATH}":/usr/local/bin:"${PATH}"

export CASTLE_SNAPSHOTS_PATH="${HOME}/public_html/castle-engine-snapshots"

# prepare output path and log file
export OUTPUT_PATH="${CASTLE_SNAPSHOTS_PATH}"`date +%F`/
mkdir -p "$OUTPUT_PATH"
OUTPUT_LOG="$OUTPUT_PATH"compilation_output.log

# make empty "$OUTPUT_LOG" readable ASAP
rm -f "$OUTPUT_LOG"
touch "$OUTPUT_LOG"
chmod a+rX "$OUTPUT_PATH"
chmod a+r "$OUTPUT_LOG"

# castle-engine (used to compile some stuff) uses this, also some "cd" commands may use it
export CASTLE_ENGINE_PATH="${HOME}/sources/castle-engine/trunk/"

"${CASTLE_ENGINE_PATH}"www/snapshots-scripts/castle_engine_snapshot > "$OUTPUT_LOG" 2>&1
