#!/bin/bash
set -eu

export CASTLE_ENGINE_PATH=/home/michalis/sources/castle-engine/trunk/

. "$CASTLE_ENGINE_PATH"www/pack/mk_offline_docs.sh

# Generate docs for all the files you can.
# Some exceptions are listed explicitly in 'find' params,
# most are eliminated by using CASTLE_DOCS_SKIP_INVALID.

FILE_LIST=`find "$CASTLE_ENGINE_PATH"www/htdocs/ -mindepth 1 -maxdepth 1 -iname '*.php' \
  -not -iname 'index.php' \
  -not -iname 'news_????.php' \
  -execdir echo '{}' ';' | \
  sed -e 's|\.php|.html|' -e 's|./||' | \
  sort`

export CASTLE_DOCS_SKIP_INVALID='t'

DOCS_OUTPUT="${HOME}/public_html/castle-engine-snapshots/docs/"

clean_offline_docs "${DOCS_OUTPUT}"
mk_offline_docs "${DOCS_OUTPUT}" ${FILE_LIST}
