#!/bin/bash
set -eu

# Rebuild programs in "${CASTLE_ENGINE_PATH}"
# (does a full rebuild, updating from SVN and cleaning to make
# a full build with newest sources),
# then move resulting binaries to "${CASTLE_SNAPSHOTS_PATH}" subdir.

# ----------------------------------------------------------------------------

do_svn_update ()
{
  cd "${CASTLE_ENGINE_PATH}"
  svn up
}

# ----------------------------------------------------------------------------

do_compile_tool ()
{
  echo '---------------------------------------------------------------'
  echo 'Compiling castle-engine tool'

  cd "${CASTLE_ENGINE_PATH}"
  scripts/clean_everything.sh

  cd castle_game_engine/tools/build-tool/
  ./castle-engine_compile.sh
  mv -f castle-engine "${CASTLE_BINARY_PATH}"
}

# ----------------------------------------------------------------------------

move_all_programs ()
{
  EXT="$1"
  OUT_PATH="$OUTPUT_PATH""$2"

  mkdir -p "$OUT_PATH"

  mv bezier_curves/bezier_curves"$EXT" "$OUT_PATH"
  mv castle/castle"$EXT" "$OUT_PATH"
  mv glinformation/glinformation"$EXT" "$OUT_PATH"
  mv glinformation/glinformation_glut"$EXT" "$OUT_PATH"
  mv glplotter/gen_function"$EXT" "$OUT_PATH"
  mv glplotter/glplotter"$EXT" "$OUT_PATH"
  mv glviewimage/glViewImage"$EXT" "$OUT_PATH"
  mv kambi_lines/kambi_lines"$EXT" "$OUT_PATH"
  mv malfunction/malfunction"$EXT" "$OUT_PATH"
  mv rayhunter/rayhunter"$EXT" "$OUT_PATH"
  mv view3dscene/view3dscene"$EXT" "$OUT_PATH"
  mv view3dscene/tovrmlx3d"$EXT" "$OUT_PATH"
}

do_compile_snapshot_programs ()
{
  echo '---------------------------------------------------------------'
  echo 'Compiling all programs'

  cd "${CASTLE_ENGINE_PATH}"
  scripts/clean_everything.sh

  scripts/compile_all_programs.sh
  move_all_programs '' linux-i386

  export CASTLE_FPC_OPTIONS=-Twin32
  export CASTLE_ENGINE_TOOL_OPTIONS=--os=win32
  scripts/compile_all_programs.sh
  move_all_programs '.exe' win-i386
  export CASTLE_FPC_OPTIONS=''
  export CASTLE_ENGINE_TOOL_OPTIONS=''

  export CASTLE_FPC_OPTIONS='-Twin64 -Px86_64'
  export CASTLE_ENGINE_TOOL_OPTIONS='--os=win64 --cpu=x86_64'
  scripts/compile_all_programs.sh
  move_all_programs '.exe' win-x86_64
  export CASTLE_FPC_OPTIONS=''
  export CASTLE_ENGINE_TOOL_OPTIONS=''

  echo '---------------------------------------------------------------'
  echo 'Compiled OK, moving to the "latest" symlink.'

  # Clean old snapshots, to conserve disk space.
  # Keep only snapshots from last couple of days.
  cd "${CASTLE_SNAPSHOTS_PATH}"
  set +e
  find . -mindepth 1 -maxdepth 1 \
    -type d -and \
    -name '????-??-??' -and \
    '(' -not -iname `date +%F` ')' -and \
    '(' -not -iname `date --date='-1 day' +%F` ')' -and \
    '(' -not -iname `date --date='-2 day' +%F` ')' -and \
    '(' -not -iname `date --date='-3 day' +%F` ')' -and \
    '(' -not -iname `date --date='-4 day' +%F` ')' -and \
    '(' -not -iname `date --date='-5 day' +%F` ')' -and \
    '(' -not -iname `date --date='-6 day' +%F` ')' -and \
    '(' -not -iname `date --date='-7 day' +%F` ')' -and \
    -exec rm -Rf '{}' ';'
  set -e

  # Create "latest" link, comfortable for users.
  rm -f "${CASTLE_SNAPSHOTS_PATH}"latest
  ln -s `date +%F` "${CASTLE_SNAPSHOTS_PATH}"latest

  # This will be redone at the end, but make sure now it's done --- in case something fails later
  public_html_setup_permissions.sh
}

# ----------------------------------------------------------------------------

# Not done anymore, compositing_shaders is finished now,
# final PDF version is in SVN.
#
# echo '---------------------------------------------------------------'
# echo 'Regenerate papers PDF:'
# cd "${CASTLE_ENGINE_PATH}"papers/compositing_shaders/
# make clean
# make
# mv -f compositing_shaders.pdf ~/public_html/

# ----------------------------------------------------------------------------

do_tovrmlx3d_tests ()
{
  echo '---------------------------------------------------------------'
  echo 'Runing tovrmlx3d tests:'

  cd "${CASTLE_ENGINE_PATH}"view3dscene/
  ./compile.sh
  ./run_tests.sh /tmp/view3dscene_run_tests_output.txt /tmp/view3dscene_run_tests_output_verbose.txt
  diff -u /tmp/view3dscene_run_tests_output.txt run_tests_valid_output.txt
  rm -f /tmp/view3dscene_run_tests_output.txt
}

# ----------------------------------------------------------------------------

do_engine_compile ()
{
  echo '---------------------------------------------------------------'
  echo 'Runing tests (clean and compile everything with examples):'

  cd  "${CASTLE_ENGINE_PATH}"castle_game_engine/
  make clean
  # make examples-laz first, to avoid creating .ppu colliding with Lazarus.
  make examples-laz
  make
  make examples
}

# ----------------------------------------------------------------------------

do_test_castle_window ()
{
  cd  "${CASTLE_ENGINE_PATH}"castle_game_engine/
  # Clean so we can be sure# that new -dCASTLE_WINDOW_xxx will be taken into account.
  make clean-window

  # note that we compile directly, not using compile.sh, since compile.sh
  # now uses castle-engine that does not allow passing -dXXX
  fpc -dRELEASE "$@" @castle-fpc.cfg ../view3dscene/view3dscene.lpr
}

do_castlewindow_backends_compile ()
{
  echo '---------------------------------------------------------------'
  echo 'Check CastleWindow backends compilation:'

  cd  "${CASTLE_ENGINE_PATH}"
  scripts/clean_everything.sh

  do_test_castle_window -dCASTLE_WINDOW_GTK_2
  do_test_castle_window -dCASTLE_WINDOW_XLIB
  do_test_castle_window -dCASTLE_WINDOW_GLUT
  do_test_castle_window -dCASTLE_WINDOW_TEMPLATE

  do_test_castle_window -Twin32 -dCASTLE_WINDOW_WINAPI
  do_test_castle_window -Twin32 -dCASTLE_WINDOW_GTK_2
  do_test_castle_window -Twin32 -dCASTLE_WINDOW_GLUT
  do_test_castle_window -Twin32 -dCASTLE_WINDOW_TEMPLATE

  do_test_castle_window -Twin64 -Px86_64 -dCASTLE_WINDOW_WINAPI
  # GTK2 units not available for win64?
  # do_test_castle_window -Twin64 -Px86_64 -dCASTLE_WINDOW_GTK_2
  do_test_castle_window -Twin64 -Px86_64 -dCASTLE_WINDOW_GLUT
  do_test_castle_window -Twin64 -Px86_64 -dCASTLE_WINDOW_TEMPLATE
}

# ----------------------------------------------------------------------------

do_engine_tests ()
{
  echo '---------------------------------------------------------------'
  echo 'Runing tests (auto-tests, with engine in -dRELEASE mode):'

  cd  "${CASTLE_ENGINE_PATH}"castle_game_engine/tests/
  make clean -C  ../
  make       -C  ../
  ./compile_console.sh -dNO_WINDOW_SYSTEM
  ./test_castle_game_engine -a

  echo '---------------------------------------------------------------'
  echo 'Runing tests (auto-tests, with engine in -dDEBUG mode):'

  make clean -C  ../
  # let engine be compiled by compile_console.sh, in debug mode
  ./compile_console.sh -dNO_WINDOW_SYSTEM
  ./test_castle_game_engine -a
}

# ----------------------------------------------------------------------------

do_docs ()
{
  echo '---------------------------------------------------------------'
  echo 'Making docs:'
  "${CASTLE_BINARY_PATH}"castle_engine_snapshot_remake_docs

  echo '---------------------------------------------------------------'
  echo 'Making reference using PasDoc:'
  "${CASTLE_BINARY_PATH}"castle_engine_snapshot_remake_reference
}

# main code ------------------------------------------------------------------

do_svn_update
do_compile_tool
do_compile_snapshot_programs
do_tovrmlx3d_tests
do_engine_compile
do_castlewindow_backends_compile
do_engine_tests
do_docs

echo '---------------------------------------------------------------'
echo 'Setting www-data permissions:'

public_html_setup_permissions.sh

echo "----------- That's all folks :)"
