#!/bin/bash
set -eu

. /usr/local/fpclazarus/bin/setup.sh default

export CASTLE_ENGINE_PATH=`pwd`

tools/build-tool/castle-engine_compile.sh

mkdir /tmp/jenkins-test-cge-output/

export CASTLE_ENGINE_PATH=`pwd`
cd "${CASTLE_ENGINE_PATH}/examples/2d_dragon_spine_game/"
"${CASTLE_ENGINE_PATH}/tools/build-tool/castle-engine" compile --output=/tmp/jenkins-test-cge-output/
"${CASTLE_ENGINE_PATH}/tools/build-tool/castle-engine" compile --output=/tmp/jenkins-test-cge-output/ --os=win32 --cpu=i386
"${CASTLE_ENGINE_PATH}/tools/build-tool/castle-engine" package --output=/tmp/jenkins-test-cge-output/
"${CASTLE_ENGINE_PATH}/tools/build-tool/castle-engine" package --output=/tmp/jenkins-test-cge-output/ --os=android --cpu=arm

check_file_exists ()
{
  if [ ! -f "$1" ]; then
    echo "Missing file: ${1}"
    exit 1
  fi
}

check_dir_exists ()
{
  if [ ! -d "$1" ]; then
    echo "Missing dir: ${1}"
    exit 1
  fi
}

check_file_not_exists ()
{
  if [ -f "$1" ]; then
    echo "File should not exist: ${1}"
    exit 1
  fi
}

check_dir_not_exists ()
{
  if [ ! -d "$1" ]; then
    echo "Dir should not exist: ${1}"
    exit 1
  fi
}

check_file_exists /tmp/jenkins-test-cge-output/castle_spine.exe
check_file_exists /tmp/jenkins-test-cge-output/castle_spine
check_file_exists /tmp/jenkins-test-cge-output/castle_spine-1.1-linux-x86_64.tar.gz
check_file_exists /tmp/jenkins-test-cge-output/castle_spine-1.1-win32-i386.zip
check_dir_exists /tmp/jenkins-test-cge-output/castle-engine-output

check_file_not_exists castle_spine.exe
check_file_not_exists castle_spine
check_file_not_exists castle_spine-1.1-linux-x86_64.tar.gz
check_file_not_exists castle_spine-1.1-win32-i386.zip
check_dir_not_exists castle-engine-output
