#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Not needed, let android_setup.sh set FPC version.
# . /usr/local/fpclazarus/bin/setup.sh default

. /usr/local/android/android_setup.sh

export CASTLE_ENGINE_PATH=`pwd`
export OUTPUT_PATH="/tmp/jenkins-test-cge-output-$$/"

# ----------------------------------------------------------------------------
# compile build tool

tools/build-tool/castle-engine_compile.sh
export CGE_BUILD_TOOL="${CASTLE_ENGINE_PATH}/tools/build-tool/castle-engine"

# ----------------------------------------------------------------------------
# compile 2d_dragon_spine_game to temporary output path

mkdir "${OUTPUT_PATH}"
function finish {
  rm -Rf "${OUTPUT_PATH}"
}
trap finish EXIT

export CASTLE_ENGINE_PATH=`pwd`
cd "${CASTLE_ENGINE_PATH}/examples/2d_dragon_spine_game/"
"${CGE_BUILD_TOOL}" compile --output="${OUTPUT_PATH}"
"${CGE_BUILD_TOOL}" package --output="${OUTPUT_PATH}" --fast
"${CGE_BUILD_TOOL}" package --output="${OUTPUT_PATH}" --os=win32 --cpu=i386 --fast
"${CGE_BUILD_TOOL}" package --output="${OUTPUT_PATH}" --os=android --cpu=arm --fast

# ----------------------------------------------------------------------------
# check stuff does/doesn't exist

check_file_exists ()
{
  if [ ! -f "$1" ]; then
    echo "Missing file: ${1}"
    exit 1
  fi
}

check_dir_exists ()
{
  if [ ! -d "$1" ]; then
    echo "Missing dir: ${1}"
    exit 1
  fi
}

check_file_not_exists ()
{
  if [ -f "$1" ]; then
    echo "File should not exist: ${1}"
    exit 1
  fi
}

check_dir_not_exists ()
{
  if [ ! -d "$1" ]; then
    echo "Dir should not exist: ${1}"
    exit 1
  fi
}

check_file_exists "${OUTPUT_PATH}"castle_spine.exe
check_file_exists "${OUTPUT_PATH}"castle_spine
# this matches OS/arch where Jenkins is installed
check_file_exists "${OUTPUT_PATH}"castle_spine-1.1-linux-i386.tar.gz
check_file_exists "${OUTPUT_PATH}"castle_spine-1.1-win32-i386.zip
check_dir_exists "${OUTPUT_PATH}"castle-engine-output

check_file_not_exists castle_spine.exe
check_file_not_exists castle_spine
# this matches OS/arch where Jenkins is installed
check_file_not_exists castle_spine-1.1-linux-i386.tar.gz
check_file_not_exists castle_spine-1.1-win32-i386.zip
check_dir_not_exists castle-engine-output
