#!/bin/bash
set -eu

cd ~/sources/vrmlengine/trunk/www/scripts/offline_docs/

export VRMLENGINE_HTDOCS_LOCAL_PATH=/home/michalis/sources/vrmlengine/trunk/www/htdocs/

HTMLS="kambi_vrml_extensions.html \
kambi_vrml_extensions_shadow_maps.html \
kambi_vrml_extensions_vrml1.html \
kambi_vrml_extensions_screen_effects.html \
vrml_implementation_cadgeometry.html \
vrml_implementation_core.html \
vrml_implementation_cubemaptexturing.html \
vrml_implementation_environmentaleffects.html \
vrml_implementation_environmentalsensor.html \
vrml_implementation_eventutilities.html \
vrml_implementation_geometry2d.html \
vrml_implementation_geometry3d.html \
vrml_implementation_grouping.html \
vrml_implementation_hanim.html \
vrml_implementation_interpolation.html \
vrml_implementation_keydevicesensor.html \
vrml_implementation_lighting.html \
vrml_implementation_navigation.html \
vrml_implementation_networking.html \
vrml_implementation_nurbs.html \
vrml_implementation_pointingdevicesensor.html \
vrml_implementation_rendering.html \
vrml_implementation_scripting.html \
vrml_implementation_shaders.html \
vrml_implementation_shape.html \
vrml_implementation_sound.html \
vrml_implementation_status.html \
vrml_implementation_text.html \
vrml_implementation_texturing3d.html \
vrml_implementation_texturing.html \
vrml_implementation_time.html \
vrml_x3d.html \
nist_vrml_test_suite.html \
kanim_format.html \
vrml_time_origin_considered_uncomfortable.html \
kambi_script.html"

make clean $HTMLS LOCALLY_AVAIL="$HTMLS"

OUTPUT=~/public_html/vrmlengine-snapshots/docs/
mv -f $HTMLS $OUTPUT
cp -f ~/sources/vrmlengine/trunk/www/htdocs/shadow_maps_x3d.pdf $OUTPUT
cp -f ~/sources/vrmlengine/trunk/www/htdocs/vrmlengine.css $OUTPUT
mkdir -p $OUTPUT/images
cp -f ~/sources/vrmlengine/trunk/www/htdocs/images/header*.png $OUTPUT/images

