# Android Services
include::common.adoc[]

== Introduction

cgeimg::block[android-components-icons.png|Android Services]

When you package your game for Android, you can easily add _services_ to the project. They allow to comfortably access various Android services (from Google and other 3rd parties, like ad networks) from your Object Pascal game code using the https://castle-engine.io/[Castle Game Engine].

The Android services are declared in link:project_manifest[CastleEngineManifest.xml] like this:

[source,xml]
----
<android>
  <services>
    <service name="google_play_services" />
    <service name="google_in_app_purchases" />
  </services>
</android>
----

== List of Services

* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/admob/README.adoc[admob]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/apps_flyer/README.adoc[apps_flyer]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/chartboost/README.adoc[chartboost]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/client_server/README.adoc[client_server]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/download_urls/README.adoc[download_urls]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/facebook/README.adoc[facebook]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/freetype/README.adoc[freetype]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/game_analytics/README.adoc[game_analytics]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/google_in_app_purchases/README.adoc[google_in_app_purchases]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/google_play_games/README.adoc[google_play_games]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/google_play_services/README.adoc[google_play_services]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/helpshift/README.adoc[helpshift]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/sound/README.adoc[sound]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/startapp/README.adoc[startapp]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/tenjin/README.adoc[tenjin]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/test_fairy/README.adoc[test_fairy]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/ogg_vorbis/README.adoc[ogg_vorbis]
* https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/photo_service/README.adoc[photo_service]
* https://github.com/castle-engine/castle-engine/blob/master/tools/build-tool/data/android/integrated-services/png/README.adoc[png]
* https://github.com/castle-engine/castle-engine/blob/master/tools/build-tool/data/android/integrated-services/read_external_storage/README.adoc[read_external_storage]
* https://github.com/castle-engine/castle-engine/blob/master/tools/build-tool/data/android/integrated-services/vibrate/README.adoc[vibrate]
* https://github.com/castle-engine/castle-engine/blob/master/tools/build-tool/data/android/integrated-services/write_external_storage/README.adoc[write_external_storage]

=== Past (removed) services

The Android ecosystem is dynamic, and some products just disappear and/or are replaced by something very different over time. As such, some of our past services are no longer available:

* _Giftiz_: Service no longer available, as the company developing it (and maintaining the server) is no longer available.

* _Heyzap_: Service no longer available. The company behind it was acquired by _Fyber_. Which was later acquired by _Digital Turbine_. Perhaps the https://developer.digitalturbine.com/hc/en-us/sections/360002898457-FairBid-Android-Configuration[SDK from Digital Turbine] can offer similar functionality, but we didn't test it yet.

* _Google Analytics_: It has been https://developers.google.com/analytics/devguides/collection/android/v4/[deprecated by Google] and, while it still compiles, it crashes on new devices:
+
```
 FATAL EXCEPTION: main
Process: net.sourceforge.castleengine.dragonsquash, PID: 19322
java.lang.IllegalArgumentException: net.sourceforge.castleengine.dragonsquash: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:378)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:648)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:635)
  ...
	at com.google.android.gms.analytics.GoogleAnalytics.getInstance(Unknown Source:15)
	at net.sourceforge.castleengine.ServiceGoogleAnalytics.getAppTracker(ServiceGoogleAnalytics.java:58)
  ...
```
+
Google recommends to migrate to their https://firebase.google.com/[Firebase SDK]. Not implemented in CGE yet (but may be in the future).
+
Currently the best mobile analytics, integrated with CGE on both Android and iOS, are provided by https://github.com/castle-engine/castle-engine/tree/master/tools/build-tool/data/android/integrated-services/game_analytics/README.adoc[game_analytics] service.

== How it works

While the base _Castle Game Engine_ activity on Android uses `NativeActivity`, we add Java code to integrate with additional services you request.

The link:build_tool[build tool] will automatically create Android project that contains all the necessary services, and it will invoke Android tools to build and run it.

== Default features of integrated projects

Even if you don't add any services explicitly, by default the following features are available:

* _Immersive mode_. This is a "true" full-screen mode for games on Android, where the back/home buttons are usually hidden.

* You can open URLs in external applications using cgeref:OpenURL[].
+
NOTE: Open special `market://` URL on Android to send users to the _Google Play_ store, e.g. to rate your application.

* You can share text and links with other applications using cgeref:ShareText[]. This allows to e.g. propose users to send a message with a link to your game to their friends.

* You can send Android standard on-screen notification ("toast") using cgeref:OnScreenNotification[].

* Some services (like `sound` and `ogg_vorbis`) will be added automatically to your project if the sound files are detected in your game data.

== Adding new services

See link:adding_new_android_services[Adding New Android Services].
