# Camera
include::common.adoc[]

## Introduction

Camera determines what do you see in the viewport.

It defines 3 vectors:

. cgeref:TCastleCamera.Position[] - observer position.
. cgeref:TCastleCamera.Direction[] - direction in which you look.
. cgeref:TCastleCamera.Up[] - together with _direction_, the _up_ vector determines the camera _orientation_.

Camera also defines _projection_:

* cgeref:TCastleCamera.ProjectionType[] - determines _perspective_ or _orthographic_ projection.
* cgeref:TCastleCamera.Perspective[], cgeref:TCastleCamera.Orthographic[] - these subcomponents allow to configure projection details.

See the link:viewport_3d[Tutorial: Designing a 3D world] and link:viewport_3d[Tutorial: Designing a 2D world] to see the typical workflow how do you manipulate the camera using the editor.


## The initial camera

There are various ways to set the initial camera:

- If you design your world using the _Castle Game Engine editor_, we recommend to set the initial camera following the link:viewport_3d[Tutorial: Designing a 3D world]. This means that you navigate to set the best camera, and then use _"Camera Current := Initial (stored in the design file)"_ command.

- Another approach is to just set the camera vectors by code during your state start. Call cgeref:TCastleCamera.SetView[Viewport.Camera.SetView] like this:
+
[source,pascal]
----
Viewport.Camera.SetView(
  Vector3(-11.34, 30.04, 96.07), // position
  Vector3(0.10, -0.49, -0.87), // direction
  Vector3(0.35, 0.83, -0.43), // up (current)
  Vector3(0.00, 1.00, 0.00) // gravity up
);
----
+
You can even generate such Pascal code: Use the _"Clipboard -> Print Current Camera (Viewpoint) (Pascal)"_ menu item in link:view3dscene.php[view3dscene].

- Alternatively, automatically initialize the camera defaults (including position, direction, up vectors) based on the information in the model.
+
To activate this auto-detection, set cgeref:TCastleViewport.AutoCamera[] to `true`.
+
The way this auto-detection works:
+
--
- If the scene set as cgeref:TCastleRootTransform.MainScene[Viewport.Items.MainScene] defines a default camera, then use it.
+
For example link:gltf[glTF] format allows to define a default camera. link:creating_data_blender.php[Blender] can export such glTF models.
+
Models in In X3D can also define a default camera, using X3D `Viewpoint` or `OrthoViewpoint` nodes. If you write X3D files by hand, you can even generate such nodes using the _"Console -> Print Current Camera (Viewpoint)"_ menu item in link:view3dscene.php[view3dscene].

- Otherwise (if there is no `Viewpoint` node,or you didn't even set `MainScene`) then the camera will be auto-detected to look at the world bounding box.
--
