# The Castle - credits
include::common.adoc[]
:description: Credits for The Castle game made with Castle Game Engine.

== Authors

Credits for link:castle_game[The Castle] game.

https://michalis.xyz/[Michalis Kamburelis] did the whole programming and most of the 3D modelling.

_Szymon Stoma and Kaśka Zaremba_ designed and modelled the scenario on "The Gate" level (all models in `data/levels/gate/gate_parts/`), modelled many 3D objects (keys, bow, quiver, arrows, ball_missile_s), provided some sounds and a large amount of feedback.

_Grzegorz Hermanowicz_ implemented underwater "sick" projection effect and started gravity for arrows implementation.

_Michał Wojtkiewicz_ provided the `levels/gate/tree` model.

_Great thank you to everyone who contributed!_

== Software used when developing this game

* link:index.php[Castle Game Engine]. The base of our game.
+
We also used some engine tools and accompanying programs: link:rayhunter[rayhunter] was used to render some items 2D images (see `data/items/xxx/image.png`), link:castle-model-viewer[Castle Model Viewer] was used to test and slightly edit 3D models, and to make many screenshots.

* http://www.freepascal.org/[Free Pascal Compiler]

Graphics:

* http://www.blender3d.org/[Blender]
* http://www.gimp.org/[GIMP]
* http://www.imagemagick.org/script/index.php[ImageMagick]
* http://www.planetside.co.uk/terragen/[Terragen] was used to create skies (see `data/skies/`).
* Some post-processing of VRML models was done using EmacsLisp. See `data/kambi-castle-utils.el` and various Makefiles, like `data/levels/gate/Makefile`.

Sounds:

* http://www.metadecks.org/software/sweep/[Sweep] and http://audacity.sourceforge.net/[Audacity] were used to edit sounds.
* http://sox.sourceforge.net/[Sox] was used for some batch processing of sounds.

== Data used in this game

While most of the data used by the game was done by "The Castle" team (see <<Authors>> above), some data was obtained from the Internet, under various "free" licenses. Unfortunately, not 100% of them are really FOSS compatible, but we're working on it. See `castle/data/AUTHORS.txt` for details.

The larger data collections used:

* Many textures from public domain _Golgotha_ textures. They were hosted on various websites on the Internet, currently you can get (most) of them from http://opengameart.org/content/golgotha-textures[opengameart.org Golgotha useful textures collection].
* Many tileable textures with excellent quality from http://www.lemog.fr/lemog_textures/index.php[Lemog tileable textures].
* Many public domain sounds and music from http://www.flashkit.com/[Flash Kit].

=== DOOM E1M1 bonus level

Inside the game I added, as a joke/experiment/tribute, a level based on well-known http://www.idsoftware.com/[id Software] game "Doom". Level geometry and textures come from original DOOM E1M1 level, the level is just converted to VRML (and changed in many places for my engine).

Thanks go to whole Id staff that produced DOOM. For a lot of technical details how DOOM E1M1 level was done in my game, see the file `data/levels/doom/e1m1/README.txt` in game data. Music is taken from great http://www.sirgalahad.org/paul/doom/["DOOM I and II Music" as compiled by Paul Burdette].

[NOTE]
====
_Legal things_:

*For distro packagers*: remember that the Doom level and it's resources (i.e. most of the things inside directories `data/levels/doom/e1m1/`, `data/textures/doom/`, `data/sounds/doom/` and `data/skies/doom/`) are not open-source, are not covered by GNU GPL license, are not under my (Michalis Kamburelis) copyright etc. Legally, I guess that they are a heavily processed version of the content that was originally developed by Doom authors, and they own it.

If you want to redistribute my game as a pure open-source, you can simply remove these `doom/` subdirectories. The DOOM level will then disappear from the "New Game" menu.

*For Id Software*: hopefully if any lawyer working for Id Software will ever spot this page, he will understand that the "Doom level" in my game is

* Partially a joke and an experiment (how Doom level will look when rendered in modern technology, with free 3D and OpenGL and all).
* Partially a tribute to Doom.
* I include only the very first Doom level, E1M1, that is virtually known to every person who ever played any computer game, it was even released as a shareware after all.
* The "Doom level" is not a main level of my game, it's just a bonus.

So don't sue me. Thanks :)
====
