# CastleWindow Backends
include::common.adoc[]

== Introduction

cgeref:TCastleWindow[] class represents a window suitable for _Castle Game Engine_ rendering.

Most CGE applications use this class (although there is an alternative https://castle-engine.io/manual_lazarus_control.php[TCastleControl], but we advise `TCastleWindow` for most cases).

The `TCastleWindow` has a number of alternative _backends_, using different libraries underneath to manage the window and OpenGL(ES) context properties. By default, we use a backend that is considered "best" for the current operating system you're compiling to, but you can override this choice by defining a symbol `CASTLE_WINDOW_xxx` at the compilation time. You can define this symbol in various places, e.g. https://castle-engine.io/project_manifest#compiler-options-and-paths[in CastleEngineManifest.xml file].

Right now, we always use exactly one "backend", which is determined at the compile-time when you compile your application. In the future, we want to rework the CastleWindow infrastructure to enable you to use multiple backends, each backend in a separate unit, and (optionally) allow you to select the best backend at runtime.

== Available backends

=== WinAPI (CASTLE_WINDOW_WINAPI)

The default backend on Windows. Looks native and supports everything.

Uses Windows API (WinAPI). By default it uses `wgl` to initialize OpenGL context. Can be also used (when symbol `OpenGLES` is defined) to initialize OpenGLES context using EGL. This way, you can test OpenGLES rendered on desktop Windows systems.

Supported platforms:

* Windows only.

Advantages:

* `TCastleWindow.MainMenu` is implemented as actual Windows menu bar, so it looks good and native.
* Dialog windows like `TCastleWindow.FileDialog` are implemented using standard Windows dialog boxes, so again they look nice and native.
* Supports both OpenGL (by `wgl`) and OpenGLES (by `EGL`) contexts.

=== GTK 3 (CASTLE_WINDOW_GTK_3)

cgeimg::block[window_gtk3.png|TCastleWindow with GTK 3 backend]

The default backend on most Unix systems, like _Linux_ and _FreeBSD_. Looks native and supports everything. Uses https://docs.gtk.org/gtk3/[GTK 3]. Initializes context using

- Xlib + glX (_OpenGL_ context)
- EGL (_OpenGLES_ or _OpenGL_ context, depending on the `OpenGLES` symbol being defined).

Supported platforms:

* Works on any OS where GTK + glX / EGL works. Currently tested under _Linux_, _FreeBSD_.

Almost all features of cgeref:TCastleWindow[] API are supported and look good (native):

* Menu bar (cgeref:TCastleWindow.MainMenu[]) is implemented using GTK menu bar.

* Dialog windows (cgeref:TCastleWindow.FileDialog[], cgeref:TCastleWindow.ColorDialog[], cgeref:TCastleWindow.MessageOK[], cgeref:TCastleWindow.MessageYesNo[]) are implemented using GTK dialogs.

* Fullscreen toggling (cgeref:TCastleWindow.FullScreen[]) is implemented using GTK features.

* Cursor hiding and mouse position setting works as expected. So _mouse look_ works OK.

Known problems:

* `Tab` key cannot work as menu item shortcut (it's always only for switching focus). This is an issue with GTK 2.

* `Application.TryVideoChange` (to change screen resolution at runtime) is not finished, i.e. always returns false. See TODOs near `CASTLE_WINDOW_USE_XF86VMODE` definition.

History: at some point this was using _GtkGlExt_. This has changed, to use glX / EGL directly, because:

* This way our runtime dependencies are simpler (not every system has _GtkGlExt_),

* We needed code dealing with glX and EGL directly anyway (for other backends, like `CASTLE_WINDOW_XLIB` and `CASTLE_WINDOW_ANDROID`), so it makes sense to reuse their logic.

=== GTK 2 (CASTLE_WINDOW_GTK_2)

_Deprecated._ Older version of the GTK backend, using GTK 2.

Use only if absolutely necessary. link:talk.php[Tell us if you need this], otherwise at some point we will remove it.

=== Xlib (X11) (CASTLE_WINDOW_XLIB)

A backend useful on most Unix systems, like Linux, that use X11.

Advantages compared to `CASTLE_WINDOW_GTK` (which supports similar platforms):

* Doesn't depend on GTK (one less dependency of your application).
* `Application.TryVideoChange` works.
* Supports both OpenGL (by `glX`) and OpenGLES (by `EGL`) contexts. By default it uses `glX` to initialize OpenGL context. But when symbol `OpenGLES` is defined, it uses EGL to initialize OpenGLES context. This way, you can test OpenGLES renderer on desktop Unix systems.

Known problems:

* Doesn't provide nicely-looking menu bar (`TCastleWindow.MainMenu`). Menu bar is not visible.
* Doesn't provide nicely-looking dialog boxes (`TCastleWindow.FileDialog`). The dialog boxes are implemented using simple modal boxes in `CastleMessages` instead, which works OK but doesn't look pretty.
* Full-screen (`TCastleWindow.FullScreen`) is realized using an obsolete method ("override_redirect") that doesn't allow to switch applications with Alt+Tab from a fullscreen window.

=== Form (LCL or FMX) (CASTLE_WINDOW_FORM)

Backend that uses `TForm` and other LCL / FMX components to create a window. It is fully-functional:

- of course, has OpenGL rendering area filling the window,
- supports main menu (cgeref:TCastleWindow.MainMenu[]),
- supports native dialogs (cgeref:TCastleWindow.FileDialog[] and others)
- supports fullscreen toggling (cgeref:TCastleWindow.FullScreen[]).

To use this define `CASTLE_WINDOW_FORM`.

It is automatically used right now when you compile with Delphi for non-Windows platforms (Linux, macOS, Android, iOS...).

Moreover, to use this from Lazarus (LCL):

* Add `castle_engine_lcl` package to the requirements of the `castle_engine_window` Lazarus package.
+
It will also automatically add `LazOpenGLContext` package as dependency, which is good. We need `castle_engine_lcl` package for LCL helpers (like converting mouse/keys between LCL and CastleKeysMouse), and we need `LazOpenGLContext` package for TOpenGLControl.

* Or you can use `alternative_castle_engine_window_based_on_lcl.lpk` instead of `castle_engine_window.lpk` in the project. This should take care of above 2 things.

* Usually you should compile programs using Lazarus then (IDE or `lazbuild`), to automatically have correct LCL paths used. If you use our link:build_tool[build tool] or link:editor[CGE editor], set `build_using_lazbuild="true"` in https://castle-engine.io/project_manifest[CastleEngineManifest.xml].

Supported platforms: everywhere where LCL or FMX runs.

Advantages:

* Can use any LCL or FMX backend, so in principle allows to use `TCastleWindow` everywhere where they work.
* Even some optional (not available in all backends) features are implemented: `TCastleWindow.MainMenu` or `TCastleWindow.FileDialog` or `TCastleWindow.FullScreen`.

Known problems:

* LCL: Various small things don't work perfectly using this backend, due to small problems/unfinished features in LCL. In practice we don't advise this backend anymore with FPC or Lazarus -- for all supported platform, we have a better specialized backend when you come from FPC, that also doesn't depend on LCL.
* Screen resizing (`Application.TryVideoChange`) is not implemented. LCL doesn't implement it.
* LCL: Message loop may stutter in case of a lot of mouse movement (may be visible in case of "mouse look" navigation).
* LCL: Doesn't support OpenGLES, as underlying `TOpenGLControl` doesn't support it.

=== Android (CASTLE_WINDOW_ANDROID)

Backend using Android NDK cooperating with _Castle Game Engine_ Android activity code. Used when you compile for Android, which you should always do using our https://castle-engine.io/build_tool[build tool].

=== Library (CASTLE_WINDOW_LIBRARY)

Use existing OpenGL(ES) context. This is useful when the engine is used as a library, and an external code initializes OpenGL(ES) context, merely informing CGE about it. Useful for various cases, e.g. to "drive" Castle Game Engine rendering from another programming language. See `examples/library/` for an example of wrapping CGE in a library.

Also, this is the only possible backend to use CGE on link:ios[iOS] or link:nintendo_switch[Nintendo Switch] and it is automatically used there.

Supported platforms: All platforms. But note that using this backend requires additional "outside" code to manage our library. In case of link:ios[iOS] and link:nintendo_switch[Nintendo Switch], this is automatically provided when building using our link:build_tool[build tool].

=== Cocoa (CASTLE_WINDOW_COCOA)

Backend using https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaFundamentals/WhatIsCocoa/WhatIsCocoa.html[Cocoa] with https://developer.apple.com/documentation/appkit?language=objc[AppKit] library, coded using https://www.freepascal.org/docs-html/current/ref/refse71.html#x132-15600011.1[Objective-Pascal].
//_ (a dialect of Pascal, implemented in FPC, as an analogy to _Objective-C_ -- making some unique OOP features/misfeatures from _Objective-C_ available in Pascal).
This is the technology to create native applications on macOS.

This backend is only available for macOS, and also is the advised backend there. It gives a native look for macOS applications, and covers all standard `TCastleWindow` features:

- Opening and closing multiple windows with OpenGL context.
- Key and mouse handling, including mouse wheel events.
- cgeref:TCastleWindow.MainMenu[], realized as native macOS menu, with submenus, key shortcuts, checked, enabled menu items.
- cgeref:TCastleWindow.FileDialog[], native dialog to open/save files.
- cgeref:TCastleWindow.ColorDialog[], native dialog to pick a color.
- cgeref:TCastleWindow.MessageOK[], cgeref:TCastleWindow.MessageYesNo[] - native alerts to notify about something or ask a question.
- Opening associated files on macOS, see link:project_manifest#_associated_file_types[CastleEngineManifest.xml - Associated file types], is also supported with some necessary code in this backend.

Known problems:

- TODO: Fullscreen is not correct. The menu bar and macOS dock remain visible, covering parts of the fullscreen window. We have a code in place to deal with it... unsuccessfully, so far.
- TODO: Hiding mouse cursor doesn't work. Again we have a code to hide/unhide cursor, but it doesn't work properly for unknown (yet!) reason.
- When building, a few messages like `warning: section "\__datacoal_nt" is deprecated: .section __DATA, __datacoal_nt, coalesced` are displayed. https://wiki.lazarus.freepascal.org/Mac_Installation_FAQ#Lazarus_reports_success.2C_but_there_are_errors.21[Compiling LCL app on macOS shows these warnings too]. There is no solution for now, but the warnings can be safely ignored.

////
=== Obsolete: DispmanX (CASTLE_WINDOW_DISPMANX)

Use the Castle Game Engine on the Raspberry Pi under Linux (tested with Raspbian) without X or Wayland.

Obsolete: This is only available in a fork, and no longer maintained.

See link:pass:[DispmanX backend][] for details.
////

=== Web (CASTLE_WINDOW_WEBASSEMBLY)

Backend used on the link:web[]. Communicates with the browser environment, in particular with the WebGL context in an HTML `<canvas>`, using JavaScript APIs.

=== Template (CASTLE_WINDOW_TEMPLATE)

A dummy backend that does nothing, but compiles. Can be used as a starting point when developing new CastleWindow backends.

Supported platforms: All platforms.

== Making new backend

* Invent a symbol `CASTLE_WINDOW_FOO` for a new backend, document it in the "available backends list" above.
* Create a file `castlewindow_foo.inc` with contents from  `castlewindow_backend_template.inc` and conditionally include it from `castlewindow_backend.inc`.
* Adjust defining `CASTLE_WINDOW_HAS_VIDEO_CHANGE` and `CASTLE_WINDOW_USE_PRIVATE_MODIFIERS_DOWN`  for your backend.
* Implement all methods in `castlewindow_foo.inc`.
* Call `TCastleWindow.DoXxx` functions at appropriate places from your backend. You can call all `DoUpdate` all `Application.OpenWindows` using `Application.FOpenWindows.DoUpdate`.
* Call `ApplicationProperties._Update` when appropriate. Remember that you can always assume that the ONLY existing instance of `TCastleApplication` is `Application`.
* Remember that probably you will have to call `ReleaseAllKeysAndMouse` when user switches to another window or activates MainMenu.
