# Curves Tool
include::common.adoc[]

cgeimg::float[castle_curves.png|Tool to design curves]

== Introduction

We have a simple tool to design curves (piecewise cubic Bezier curves). The created curves can be saved into a simple XML format and loaded into your own Castle Game Engine programs and used for any purpose (for example as a track along which something moves).

Download:

* Get https://castle-engine.io/[Castle Game Engine binary release], the tool is readily available as `bin/castle-curves` .
* Or get https://github.com/castle-engine/castle-engine/[Castle Game Engine source code], the tool is in `tools/castle-curves` subdirectory.

The main example how to use designed curves is inside the CGE, in https://github.com/castle-engine/castle-engine/tree/master/examples/curves/use_designed_curve[examples/curves/use_designed_curve].

== Creating and editing curves

For many commands and their key shortcuts, see the program's menu. Use mouse to create and edit curve points:

* Right mouse button click:
+
_Add new_ curve point. If some curve and point were selected, the new point is added to the selected curve _after the selected point_. Otherwise, a new new curve with one point is created. So if you want to start creating 2nd curve, just deselect all (key _N_) and press right mouse button.

* Left mouse button click:
+
_Select_ control point (and it's curve).

* Dragging with left mouse button:
+
_Move_ selected point. Hold _Shift_ key to move whole selected curve. The smallest drags are ignored at the begging, so we avoid accidental drags when selecting, don't worry:)

* Use keys + and - to smoothly zoom in/out. Use Home to reset zoom to zero.

TIP: use a reference image (menu _Background->Load_) to fit your curve nicely to your use. By default we show a simple image with a helpful grid.

_Save_ and _open_ menu commands store curves list in a simple XML file. You can use it to load your designed curves into your Castle Game Engine programs, see below.

== Using curves in your own programs

* Load a list of curves from XML file using the `TCurveList.LoadFromFile` method.
* Or load the first curve from XML file using the simpler `TCurve.LoadFromFile` method.
* Query the curve using the `TCurve.Point(T)` method.
* Use T values in the range [0..1] to move along the curve. In general, you should look at the valid range for T in `TCurve.TBegin` and `TCurve.TEnd` properties, but in case of castle-curves tool -- you know that `TBegin` is always 0 and `TEnd` is 1.

See the example below:

[source,pascal]
----
include::../code-samples/curves_example.dpr[]
----
