# Dedicated GPU
include::common.adoc[]

== Introduction

Many laptops come with 2 graphics cards (GPUs):

1. a slower one, that consumes less battery,

2. and a _"dedicated"_ GPU consuming more battery but more powerful. It is faster, esp. with non-trivial 3D data.

Our editor and your applications automatically use the "dedicated" GPU.

NOTE: There's generally no need to do anything for new projects to activate this. Project DPR / LPR file will contain appropriate code automatically. To make sure this is active, and follows our template, use the engine editor menu item _"Code -> Regenerate Project"_.

== Disable using dedicated GPU

Applications created using our engine will automatically use dedicated GPU by default on _Windows_, as this is a much better default for games. However you can choose to disable it, and let system choose the default GPU (which may or may not be the faster one).

To do this, compile the project with `CASTLE_NO_FORCE_DEDICATED_GPU` symbol defined. We recommend to define it in link:project_manifest[CastleEngineManifest.xml], like this:

[source,xml]
----
...
  <compiler_options>
    <defines>
      <define>CASTLE_NO_FORCE_DEDICATED_GPU</define>
    </defines>
  </compiler_options>
----

To update Lazarus LPI with new symbol, be sure to use _"Code -> Regenerate Project"_ menu item in CGE editor (otherwise compiling from Lazarus IDE would not use the new symbol).

[WARNING]
====
The mechanism to request dedicated GPU only works on _Windows_. We're not aware of a way to request dedicated GPU on other systems.

Users can request using dedicated GPU on their side. E.g. in _GNOME 3_ (Linux, FreeBSD etc.), you can right-click on the application and select _"Run with Dedicated Graphics Card"_. You can also use `prime-run` command line tool if provided.
====

== Credits and references

Our code to make it happen is based on https://www.patreon.com/bero[Benjamin Rosseaux] code from https://gist.github.com/BeRo1985/939241b471f776ab844657d28d59368c .

NVidia resources about this:

- https://docs.nvidia.com/gameworks/content/technologies/desktop/optimus.htm

- https://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf
