# Download
include::common.adoc[]

== Download the engine for your system

cge::download-engine[7.0-alpha.snapshot,snapshot]

NOTE: To build applications using the engine you also need to install a _compiler_. The _Windows_ and _Linux_ downloads already contain the latest stable version of https://www.freepascal.org/[FPC], so you can build and run projects out-of-the-box. If you want more, read link:install[the manual about installation].

== Alternative download and installation options

=== GitHub releases with more variants (like downloads not bundled with FPC)

More downloads are available on https://github.com/castle-engine/castle-engine/releases/latest . They contain:

- Alternative "non-bundled" versions for some platforms (without the `-bundle` in zip name). Use them if you want to install the Pascal compiler (like https://www.freepascal.org/[FPC] or https://www.embarcadero.com/products/Delphi[Delphi]) yourself. Remember to point CGE to your compiler using the _"Preferences"_ editor window.

- For Windows, alternative zip versions instead of self-installing exe.

- Win32 platform, which we still support but discourage. The world has largely moved to 64-bit (for Windows and other OSes) so we recommend using Win64.

=== Itch.io

Head over to https://castle-engine.itch.io/castle-game-engine[Castle Game Engine on itch.io] to download the engine from Itch.io.

For extra comfort, use https://itch.io/app[itch.io app]. It's very nice and allows to download + install the engine, or later update, with really 1 click.

NOTE: This installs the latest _released_ engine version, like `7.0-alpha.2`. Not a snapshot.

=== Arch Linux User Repository

link:https://archlinux.org/[Arch Linux] users can install Castle Game Engine from link:https://wiki.archlinux.org/title/Arch_User_Repository[AUR (Arch User Repository)].

The package is available on link:https://aur.archlinux.org/packages/castle-engine-git/[https://aur.archlinux.org/packages/castle-engine-git/] . Follow the standard AUR installation process:


* Do it manually following link:https://wiki.archlinux.org/title/Arch_User_Repository[AUR] docs, like
+
```
wget https://aur.archlinux.org/cgit/aur.git/snapshot/castle-engine-git.tar.gz
tar xzvf castle-engine-git.tar.gz
cd castle-engine-git/
makepkg -sri
```

* Or use a helper like link:https://aur.archlinux.org/packages/paru/[paru]. Once you have it working, just use `paru -S castle-engine-git`.

NOTE: This installs the latest engine version from the https://github.com/castle-engine/castle-engine/[GitHub repository (master branch)]. Bleeding edge! (But in practice, often stable to be used even for production work.)

////
== Debian / Ubuntu packages

Castle Game Engine is available in Debian and Ubuntu through the official packages, albeit in slightly outdated versions.

https://packages.debian.org/search?suite=sid&searchon=names&keywords=castle-game-engine
////

=== Delphinus

WARNING: Downloading CGE this way is not yet reliable, see https://github.com/castle-engine/castle-engine/issues/84[here].

link:https://github.com/Memnarch/Delphinus/[Delphinus] is an open-source package manager for https://www.embarcadero.com/products/Delphi[Delphi]. You can use it to install _Castle Game Engine_ within Delphi IDE.

- The nice benefit is that it will automatically modify your Delphi settings, to make CGE units available for all the projects.
+
This means you can use CGE units for all projects, without the need to add all necessary CGE paths manually (to Delphi settings or to DPROJ) and without using CGE build tool to manage your DPROJ.

- The drawback is that it will not install the binary tools, like CGE editor. _Delphinus_ only downloads the contents of CGE repository -- which means CGE source code.
+
For this reason, we advise to install CGE from the standard installer (see higher on this page) too, and run CGE editor from it. As long as you use the same CGE version, it will work fine.
+
Alternatively, you may follow https://castle-engine.io/compiling_from_source.php[compiling CGE from sources] to get CGE editor.

Instructions:

. *Install Delphinus*
+
--
. Clone GIT repository https://github.com/Memnarch/Delphinus/

. Open in your Delphi the package `Delphinus\Packages\DelphiXE6\Delphinus.dproj`.
+
NOTE: This package file assumes you have Delphi >= Delphi XE 6, which is almost certain today.

. Compile and Install this package in Delphi.

. You will get a new menu item _"Tools -> Delphinus_" in Delphi. Use it to see the _Delphinus_ GUI.
+
cgeimg::block[delphinus_1.png|Delphinus GUI]
--

. **Refresh packages available in Delphinus**
+
--
. You need to create _GitHub OAuth token_. When you're logged into https://github.com/[GitHub] account and visit https://github.com/settings/tokens[Developer settings -> Personal access tokens -> Tokens (classic)]. Choose _"Generate new token (classic)"_.

. On the token settings, set a name (like _"Delphinus"_), expiration time (you will have to recreate the token after that time). There's no need to select any scopes.

. Click _"Generate Token"_ at the bottom. Copy the resulting token (text `ghp_xxxxxxxx`) to the clipboard.
//Be sure to copy it before closing that page -- you will not see that token value again (if you loose it, you'll have to create a new one).

. Go back to Delphi and the Delphinus dialog window. Open Delphinus settings by clicking on the cog-wheel button on the header.
+
cgeimg::block[delphinus_2_oauth.png|Delphinus OAuth settings]

. Paste the token into the _"OAuth-Token"_ field. Click _"Test"_, if all OK (it should answer _"Authenticated as xxx"_) click _"OK"_ to save it.

. Finally click on the _"Refresh"_ button (icon with spinning arrows on the header) in Delphinus. It should download the list of packages from GitHub.
//. The list of packages in Delphinus should be now nicely filled.
--

. **Install Castle Game Engine**
+
--
. Now find _"Castle Game Engine"_ in Delphinus, click to install it. Choose version as you see fit (right now only `HEAD` is available).
+
cgeimg::block[delphinus_3_cge.png|Delphinus CGE package]

. Test it! Navigate to xxx and open some CGE example, like `examples/fps_game` and `examples/delphi/fmx`.
+
Note that in order to run some examples on Windows, you will need to place DLL files alongside the EXE file. Copy the DLL files from engine locations mentioned link:compiling_from_source.php#section_Windows[here]. Or compile the example at least once from https://castle-engine.io/manual_editor.php[CGE editor], it will copy the DLL files automatically.
--

More information in https://github.com/Memnarch/Delphinus/wiki/Installing-Delphinus[Installing Delphinus].

NOTE: Currently you have to https://github.com/Memnarch/Delphinus/[build Delphinus from source]. Installing from https://memnarch.bplaced.net/blog/delphinus/[Delphinus Websetup] is temporarily broken, see https://github.com/Memnarch/Delphinus/issues/88[Delphinus #88]. The instructions below show the approach that works now.
