# Download
include::common.adoc[]

== Download the engine for your system

cge::download-engine[7.0-alpha.snapshot,snapshot]

NOTE: To build applications using the engine you also need to install a _compiler_. The _Windows_ and _Linux_ downloads already contain the latest stable version of https://www.freepascal.org/[FPC], so you can build and run projects out-of-the-box. If you want more, read link:install[the manual about installation].

== Alternative download and installation options

=== GitHub releases with more variants (like downloads not bundled with FPC)

More downloads are available on https://github.com/castle-engine/castle-engine/releases/latest . They contain:

- Alternative "non-bundled" versions for some platforms (without the `-bundle` in zip name). Use them if you want to install the Pascal compiler (like https://www.freepascal.org/[FPC] or https://www.embarcadero.com/products/Delphi[Delphi]) yourself. Remember to point CGE to your compiler using the _"Preferences"_ editor window.

- For Windows, alternative zip versions instead of self-installing exe.

- Win32 platform, which we still support but discourage. The world has largely moved to 64-bit (for Windows and other OSes) so we recommend using Win64.

=== Itch.io

Head over to https://castle-engine.itch.io/castle-game-engine[Castle Game Engine on itch.io] to download the engine from Itch.io.

For extra comfort, use https://itch.io/app[itch.io app]. It's very nice and allows to download + install the engine, or later update, with really 1 click.

NOTE: This installs the latest _released_ engine version, like `7.0-alpha.2`. Not a snapshot.

=== Arch Linux User Repository

link:https://archlinux.org/[Arch Linux] users can install Castle Game Engine from link:https://wiki.archlinux.org/title/Arch_User_Repository[AUR (Arch User Repository)].

The package is available on link:https://aur.archlinux.org/packages/castle-engine-git/[https://aur.archlinux.org/packages/castle-engine-git/] . Follow the standard AUR installation process:


* Do it manually following link:https://wiki.archlinux.org/title/Arch_User_Repository[AUR] docs, like
+
```
wget https://aur.archlinux.org/cgit/aur.git/snapshot/castle-engine-git.tar.gz
tar xzvf castle-engine-git.tar.gz
cd castle-engine-git/
makepkg -sri
```

* Or use a helper like link:https://aur.archlinux.org/packages/paru/[paru]. Once you have it working, just use `paru -S castle-engine-git`.

NOTE: This installs the latest engine version from the https://github.com/castle-engine/castle-engine/[GitHub repository (master branch)]. Bleeding edge! (But in practice, often stable to be used even for production work.)

////
== Debian / Ubuntu packages

Castle Game Engine is available in Debian and Ubuntu through the official packages, albeit in slightly outdated versions.

https://packages.debian.org/search?suite=sid&searchon=names&keywords=castle-game-engine
////

[#delphinus]
=== Delphinus

link:https://github.com/Memnarch/Delphinus/[Delphinus] is an open-source package manager for https://www.embarcadero.com/products/Delphi[Delphi]. You can use it to install _Castle Game Engine_ within Delphi IDE.

The biggest benefit is that it will automatically modify your Delphi settings, to make CGE units available for all the projects. It also installs CGE design-time packages into Delphi, which make the link:control_on_form[TCastleControl component available to drop on Delphi FMX and VCL forms].
//This is a big convenience for Delphi users interested in link:control_on_form[TCastleControl].

NOTE: Delphi users interested in creating games solely with _Castle Game Engine_ user interface, using cgeref:TCastleWindow[] (following CGE editor templates) do not really need this. When you use CGE editor and build tool to manage your project, the project DPROJ will be automatically configured to use CGE units, and you don't need to install Delphi design-time packages.

Using Delphinus:

. *Install Delphinus.*
+
Download the https://memnarch.bplaced.net/blog/delphinus/[Delphinus Websetup]. Run the EXE inside and allow it to modify your Delphi installation.
+
Alternatively, install from sources (it's really straightforward, no worries):
+
--
. Clone GIT repository https://github.com/Memnarch/Delphinus/

. Open in your Delphi the package `Delphinus\Packages\DelphiXE6\Delphinus.dproj`.
+
NOTE: This package file assumes you have Delphi >= Delphi XE 6, which is almost certain today.

. Compile and Install this package in Delphi.
--
+
In either case, you will get a new menu item _"Tools -> Delphinus_" in Delphi. Use it to see the _Delphinus_ GUI. For more information see https://github.com/Memnarch/Delphinus/wiki/Installing-Delphinus[Installing Delphinus].
+
cgeimg::block[delphinus_1.png|Delphinus GUI]

. *Recommended: Install Castle Game Engine (from a local directory).*
+
We recommend that first you install our engine by downloading and running _Castle Game Engine_ installer, which you can download from the top of this page. This way you will have all the CGE tools (like CGE editor) and documentation available.
+
Then, use _"Install from Folder"_ button in _Delphinus_ GUI (3rd button on the toolbar). Choose the directory where you installed CGE. This is `C:\Users\<YOUR-USERNAME>\AppData\Local\Programs\Castle Game Engine\` by default.
+
NOTE: If you installed CGE from zip, or link:compiling_from_source.php[from sources], the same instructions apply. Just point Delphinus to wherever the CGE is installed. It will have a file `Delphinus.Install.json`.
+
NOTE: Installation will fail if you have previously installed Delphi packages manually. Remove them first using Delphi _"Component -> Install Packages..."_ dialog (despite the name, this dialog allows also to remove packages).

. *Alternative (not recommended): Download and install Castle Game Engine completely from Delphinus*
+
WARNING: Downloading CGE this way is not reliable, see https://github.com/castle-engine/castle-engine/issues/84[this issue].
+
We don't recommend this approach as it will not install the binary tools, like CGE editor. _Delphinus_ only downloads the contents of CGE repository -- which means CGE source code. You will have to download and install another copy of CGE independently (or https://castle-engine.io/compiling_from_source.php[compile CGE from sources]) to get CGE editor and other tools.
+
If you still want to follow this approach, read on:
+
--
. First you need to _Refresh packages available in Delphinus_ and for this you need to create _GitHub OAuth token_. When you're logged into https://github.com/[GitHub] account visit https://github.com/settings/tokens[Developer settings -> Personal access tokens -> Tokens (classic)]. Choose _"Generate new token (classic)"_.

. On the token settings, set a name (like _"Delphinus"_), expiration time (you will have to recreate the token after that time). There's no need to select any scopes.

. Click _"Generate Token"_ at the bottom. Copy the resulting token (text `ghp_xxxxxxxx`) to the clipboard.
//Be sure to copy it before closing that page -- you will not see that token value again (if you loose it, you'll have to create a new one).

. Go back to Delphi and the Delphinus dialog window. Open Delphinus settings by clicking on the cog-wheel button on the header.
+
cgeimg::block[delphinus_2_oauth.png|Delphinus OAuth settings]

. Paste the token into the _"OAuth-Token"_ field. Click _"Test"_, if all OK (it should answer _"Authenticated as xxx"_) click _"OK"_ to save it.

. Finally click on the _"Refresh"_ button (icon with spinning arrows on the header) in Delphinus. It should download the list of packages from GitHub.

. Now find _"Castle Game Engine"_ in Delphinus, click to install it. Choose version as you see fit (right now only `HEAD` is available). The final CGE directory is TODO.
+
cgeimg::block[delphinus_3_cge.png|Delphinus CGE package]
--

The end! Please test it now: Create a new VCL or FMX project, drop cgeref:TCastleControl[] on a form, build and run.

We also encourage to build and run some CGE examples, like `examples/fps_game` and `examples/delphi/fmx`. Though the examples would build fine even without using Delphinus to install (as their DPROJ files already contain all necessary paths).

NOTE: In order to run some examples on Windows, you will need to place DLL files alongside the EXE file. Copy the DLL files from engine locations mentioned link:compiling_from_source.php#section_Windows[here]. Or compile the example at least once from https://castle-engine.io/manual_editor.php[CGE editor], it will copy the DLL files automatically.
