# Download
include::common.adoc[]

== Download the engine for your system

cge::download-engine[7.0-alpha.snapshot,snapshot]

NOTE: To build applications using the engine you also need to install a compiler. We recommend installing https://www.lazarus-ide.org/[Lazarus with FPC]. More information in the link:install[manual].

== Alternative download and installation options

=== GitHub releases with more variants (like downloads not bundled with FPC)

More downloads are available on https://github.com/castle-engine/castle-engine/releases/latest . They contain:

- Alternative "non-bundled" versions for some platforms (without the `-bundle` in zip name). Use them if you want to install the Pascal compiler (like https://www.freepascal.org/[FPC] or https://www.embarcadero.com/products/Delphi[Delphi]) yourself. Remember to point CGE to your compiler using the _"Preferences"_ editor window.

- Win32 platform, which we still support but discourage. The world has largely moved to 64-bit (for Windows and other OSes) so we recommend using Win64.

=== Itch.io

Head over to https://castle-engine.itch.io/castle-game-engine[Castle Game Engine on itch.io] to download the engine from Itch.io.

For extra comfort, use https://itch.io/app[itch.io app]. It's very nice and allows to download + install the engine, or later update, with really 1 click.

NOTE: This installs the latest _released_ engine version, like `7.0-alpha.2`. Not a snapshot.

=== Arch Linux User Repository

link:https://archlinux.org/[Arch Linux] users can install Castle Game Engine from link:https://wiki.archlinux.org/title/Arch_User_Repository[AUR (Arch User Repository)].

The package is available on link:https://aur.archlinux.org/packages/castle-engine-git/[https://aur.archlinux.org/packages/castle-engine-git/] . Follow the standard AUR installation process:


* Do it manually following link:https://wiki.archlinux.org/title/Arch_User_Repository[AUR] docs, like
+
```
wget https://aur.archlinux.org/cgit/aur.git/snapshot/castle-engine-git.tar.gz
tar xzvf castle-engine-git.tar.gz
cd castle-engine-git/
makepkg -sri
```

* Or use a helper like link:https://aur.archlinux.org/packages/paru/[paru]. Once you have it working, just use `paru -S castle-engine-git`.

NOTE: This installs the latest engine version from the https://github.com/castle-engine/castle-engine/[GitHub repository (master branch)]. Bleeding edge! (But in practice, often stable to be used even for production work.)

////
== Debian / Ubuntu packages

Castle Game Engine is available in Debian and Ubuntu through the official packages, albeit in slightly outdated versions.

https://packages.debian.org/search?suite=sid&searchon=names&keywords=castle-game-engine
////
