# GitLab CI/CD
include::common.adoc[]

== Introduction

cgeimg::float[gitlab_ci.png|GitLab CI]

You can use https://docs.gitlab.com/ee/ci/[GitLab CI/CD] to automatically build your project, if you commit it to https://gitlab.com/[GitLab]. You can use the provided for free https://docs.gitlab.com/ee/ci/runners/[GitLab-hosted runners] or set up your own runner.

== Example project

We host https://gitlab.com/castle-engine/test-gitlab-ci/[test-gitlab-ci project on GitLab] specifically for the purpose of demonstrating this feature. You can open https://gitlab.com/castle-engine/test-gitlab-ci/-/pipelines[CI/CD -> Pipelines] to see the jobs it executed, their status, download their artifacts etc.

NOTE: You don't need to be logged into GitLab to see the build results.

== Usage

1. Download this file: https://gitlab.com/castle-engine/test-gitlab-ci/-/raw/master/.gitlab-ci.yml[.gitlab-ci.yml] and place it in the top-level directory of your repository.
+
NOTE: The `.gitlab-ci.yml` filename starts with a dot, this means it is a hidden file (by convention) on Unix.

2. Commit and push it, and watch the _"CI/CD"_ subsection of your project get populated with _"Pipelines"_ and _"Jobs"_. You can download the artifacts for each job.
+
By default, these are builds for Linux and Windows.

== Using Docker image with GitLab CI

The `.gitlab-ci.yml` file linked above does *not* use our link:docker[Docker images] by default. That's because our Docker images require a considerable disk space and free https://docs.gitlab.com/ee/ci/runners/[GitLab-hosted runners] are too small to unpack it.

But if you use your own runners, disk space may not be a problem. You can change the YAML file to use Docker images (to have more power and build easily e.g. also for Android). Simply uncomment the section in that file marked as `# Commented out version using Docker image`.

See link:ci[Using Castle Game Engine with any CI] for more notes how to setup FPC and _Castle Game Engine_ inside the CI job.
