# glplotter
include::common.adoc[]
:description: Drawing and generating graphs of mathematical functions.

== Introduction

_glplotter_ draws graphs of mathematical functions. You specify a mathematical expression to be used as a function, using a straightforward syntax, like "`sin(x) + x^2`".

_glplotter_ can also load a graph from a file. This is useful if your graph data doesn't come from any mathematical expression -- e.g. maybe it's some collected statistical data. Maybe your data is not even a function at all -- actually any shape consisting of line segments may be displayed by glplotter.

cgeimg::block[
  //glplotter_1.png|Screenshot from "glplotter",
  //glplotter_2.png|Screenshot from "glplotter",
  //glplotter_3.png|Screenshot from "glplotter",
  glplotter_screen_demo_1.png|Screenshot from "glplotter",
  glplotter_screen_demo_2.png|Screenshot from "glplotter",
  glplotter_screen_demo_3.png|Screenshot from "glplotter"
]

== Download

cge::download-application[
  2.1.0,
  snapshot,
  castle-engine,
  glplotter,
  glplotter,
    win64-x86_64;
    linux-x86_64;
    darwin-x86_64
]

Documentation:

== Command-line parameters

You can pass at command-line file names from which to load graphs. Dash (`-`) as filename means "standard input".

E.g. you could pipe the output of `gen_function` program to glplotter, like

[source,bash]
----
gen_function "sin(x)" -10 10 0.1 | glplotter -
----

which will display the graph of sinus for X in [-10; 10]. Commands like

[source,bash]
----
gen_function "sin(x)" -10 10 0.1 > plot.1
gen_function "x^2" -10 10 0.1 > plot.2
glplotter plot.1 plot.2
----

will display graphs of sinus and x^2^ at once. Of course, in case of function expressions, it's usually more comfortable to set them up inside glplotter using _"Functions"_ menu.

Options `--light` and `--dark` allow you to choose appropriate color scheme.

Option `--custom-size SIZE` (or `-c SIZE`) specifies size for

* grid shown when `--grid-custom` was used (or Ctrl + G pressed)
* numbers scale shown when `--num-scale-custom` was used (or Ctrl + S pressed)
* numbers shown when `--numbers-custom` was used (or Ctrl + N pressed)

See also link:opengl_options.php[standard parameters of OpenGL programs] and link:common_options.php[standard parameters of all programs].

== Graph file format

Graph for glplotter is actually just a set of line segments. They don't have to correspond to any function -- they can show any shape, they can cross each other etc.

File format:

* Lines starting with `#` (hash) are comments.
* Lines with two float numbers (separated by any whitespae) represent another point of the graph. You can use decimal or scientific float format (like `3.14` or `10e-3`). A line segment will be drawn from this point to the next one (unless a `break` will occur).
* Line with only `break` word means a break in a line segment sequence.
* Line like `name=<graph_name>` specifies graph name (will be used in glplotter legend).

Whitespace at the beginning and end of the line is always ignored.

== gen_function

`gen_function` generates graph file from given function expression. It's seldom needed -- glplotter can make a graph from function expression on it's own, see menu _"Functions"_.

Call it like:

[source,bash]
----
gen_function <function> <x1> <x2> <xstep>
----

This will write on standard output the graph of function `<function>` for x in range `[<x1> ; <x2>]` (with x sampled at each `<xstep>` distance). The graph will be in format understood by glplotter.

For example

[source,bash]
----
gen_function "x^2" 0 5 1
----

will write

----
# File generated by gen_function on 14-3-2004 at 23:34:37
#   function = x^2
#   x1 = 0
#   x2 = 5
#   xstep = 1
name=x^2
 0.0000000000000000E+0000  0.0000000000000000E+0000
 1.0000000000000000E+0000  1.0000000000000000E+0000
 2.0000000000000000E+0000  4.0000000000000000E+0000
 3.0000000000000000E+0000  9.0000000000000000E+0000
 4.0000000000000000E+0000  1.6000000000000000E+0001
 5.0000000000000000E+0000  2.5000000000000000E+0001
----

////
Removed docs: too verbose, not useful for most people...

A następne linie możnaby zapisać w bardziej czytelnej (ale równoważnej)
postaci jako:

  0 0
  1 1
  2 4
  3 9
  4 16
  5 25

Czyli lewa kolumna to po kolei numbers od 0 do 5 (co 1) a prawa kolumna
to wartości funkcji `x^2` (czyli x^2^) gdzie x to wartość
w lewej kolumnie.

Polecenia

  gen_function "x^2" 0 5 1 > plik.plot
  glplotter plik.plot

albo, krócej,

  gen_function "x^2" 0 5 1 | glplotter -

wyświetlą więc wykresik funkcji x^2^ na przedziale `[0;5]`.
////

== Syntax of mathematical expressions

Short overview of mathematical expressions syntax: this is really just normal syntax of mathematical expressions, as used in all software and resembling normal mathematical notation. When we deal with function expressions, then `x` represents the argument, e.g. `(x+4)*3+2`, `sin(x)` etc.

For detailed information about syntax and built-in functions, see link:castle_script[CastleScript language reference]. We use a subset of CastleScript syntax, allowing only a simple expression as a function expression, operating on argument "X".

////
- wylaczyc wykres 2, i 3
- podstawowe klawisze : +, - (skalowanie), strzalki (przesuwanie)
- wylaczyc siatke co 1, wlaczyc siatke + numbers co Pi
- potem wlaczyc 2, albo 3 i zaobserwowac ze wszystko sie zgadza -
  uzyc klawisza q aby zobaczyc Prawde
- reszta klawiszy : F10 (savescreen),
  pomocne zabaweczki - celownik, pktcoords, grid/ num-scale/ numbers custom,
    obracanie
- esc (wyjscie)

do tutoriala  notki o składni wyrażen. Notka o użyteczności notacji
  Iversona i ogólniej f-cji boolowskich np. mając daną funkcję
  f(x) i chcąc by była określona tylko gdy dane wyrażenie W boolowskie
  (a wiec 1 = true, 0 = false) bylo true wystarczy zrobic
  g(x) = f(x) / W (gdy W = 0 czyni funkcje nieokreslona,
  gdy W = 1 czyni g(x) = f(x))
////
