# How to render 2D games with images and sprites
include::common.adoc[]

cgeimg::float[platformer.png|Platformer]

== How to render 2D things

WARNING: This page compares 2 possible approaches to 2D rendering in CGE. This page is really *not* a good introduction into "making 2D games in CGE". For such introduction, instead follow the manual from the beginning, in particular link:viewport_and_scenes[learn about viewports, scenes] and link:viewport_2d[how to use them for 2D].

=== Full-featured option: Render using a viewport

Use cgeref:TCastleViewport[]. Add cgeref:TCastleViewport[] control to the window, and inside it draw things by creating cgeref:TCastleTransform[] descendants (like cgeref:TCastleScene[], cgeref:TCastleImageTransform[], cgeref:TCastlePlane[]).

You should call cgeref:TCastleViewport.Setup2D[] on the viewport to make it most natural for 2D games (makes camera orthographic and looking down Z axis, so your 2D world spans in XY). When using link:editor[the engine editor], use the menu item _"Add User Interface -> Viewport (2D)"_  -- it adds a cgeref:TCastleViewport[] and calls cgeref:TCastleViewport.Setup2D[] to configure it.

* Read at least these manual chapters:
 ** link:viewport_and_scenes[Viewport with scenes, camera, navigation] introduces the cgeref:TCastleScene[]. It is a versatile component that can load models from various file formats. It can play animations. Everything described in link:viewport_and_scenes[viewport and scenes] works for 3D and 2D models as well.
 ** Using cgeref:TCastleViewport[] for 2D is documented in link:viewport_2d[designing 2D worlds]. We encourage to first familiarize yourself with link:viewport_3d[3D operations], simply because the 3D tutorial is complete now, and then read link:viewport_2d[designing 2D worlds] to learn the differences for 2D.
 ** link:physics[Physics] documents how to use physics with it.
* The engine template "2D game", https://github.com/castle-engine/castle-engine/tree/master/examples/2d_games[examples in 2d_games subdirectory], https://github.com/castle-engine/castle-engine/tree/master/examples/physics[various 2D examples in physics] follow this approach.
* The important API reference links: cgeref:TCastleScene[], cgeref:TCastleSceneCore[], cgeref:TCastleViewport[].
* To render sprites you can link:sprite_sheets[load sprite sheets using TCastleScene]. You can play it's animation just like any other scene (use `Scene.PlayAnimation` method, test with link:castle-model-viewer[Castle Model Viewer] panel "Animations").
// TMI:
//+
//If you want to do it manually, you can also construct your own `TIndexedFaceSetNode` instances and change texture coordinates.

* To build a geometry from code (without loading it from a model file), you need to create a graph of X3D nodes. Various examples showing it are around the engine, the simpler is http://castle-engine.io/x3d_implementation_geometry2d.php . It instantiates a `TRectangle2DNode`. One could instead instantiate also `TIndexedFaceSetNode` which represents a free mesh, with custom texture coordinates and anything else you may need.

* To render pixel-art, set texture filtering to "nearest". It's easiest to do this by setting `Scene.RenderOptions.MagnificationFilter := magNearest`. Alternatively, you could control this on a particular shape using cgeref:TTexturePropertiesNode[].
* You can load image as cgeref:TCastleImageTransform[] (more advised) or cgeref:TCastleScene[]. See link:using_images[using images].
* To have reliable field of view (regardless of the window size in pixels, regardless of UI scaling, regardless of viewport size), set cgeref:TCastleOrthographic.Width[Camera.Orthographic.Width] or cgeref:TCastleOrthographic.Height[Camera.Orthographic.Height] to non-zero. We advise this, this is usually most natural to control viewport field of view reliably. If you create a 2D viewport in editor, we actually initialize cgeref:TCastleOrthographic.Width[Camera.Orthographic.Width] to `1000` now.
+
If both cgeref:TCastleOrthographic.Width[Camera.Orthographic.Width] and cgeref:TCastleOrthographic.Height[Camera.Orthographic.Height] are zero then viewport field of view follows window size (adjusted by UI scaling). This is not advised. It means you will have to take more care to display proper content in all cases, in all allowed viewport sizes, window sizes etc.
+
See the _"2D game"_ new project template for example.
//+
// This is true burt confusing in light of above.
//You can also use link:manual_castle_settings.php#section_ui_scaling[UI scaling] to just make cgeref:TCastleViewport[] have the same width or height, regardless of the actual window size. All the scaling is completely hidden from you, inside cgeref:TCastleViewport[] you just work in your preferred coordinates.

* You can use physics in this approach (see https://github.com/castle-engine/castle-engine/tree/master/examples/physics[various 2D examples in physics]).
* You can mix 2D and 3D freely. The cgeref:TCastleViewport.Camera[] defines projection settings and controls camera. The orthographic camera, cgeref:TCastleCamera.Orthographic[], is usually what you want for 2D games. You can insert a cgeref:TCastleScene[] with 3D content to any cgeref:TCastleViewport[], there are no restrictions like _"this viewport can only contain 2D content"_, inside the engine we don't really have any distinction like "2D content" vs "3D content".
* To use shaders, see link:shaders[] manual.
+
--
- _(Recommended)_ You can link:shaders[add shader effects] (to extend existing rendering) using `Effect` and `EffectPart` nodes.
+
To do this in Pascal (setup the nodes in Pascal), see e.g. demos https://github.com/castle-engine/castle-engine/tree/master/examples/shaders/shader_effects_simple[shader_effects_simple], https://github.com/castle-engine/castle-engine/tree/master/examples/shaders/shader_effects_on_shape[shader_effects_on_shape].
+
To do this in X3D (editing X3D file), see https://github.com/castle-engine/demo-models[our demo models], in particular https://github.com/castle-engine/demo-models/tree/master/compositing_shaders[compositing_shaders] subdirectory.

- _(Not Recommended)_ You can _override_ standard engine shaders using `ComposedShader` and `ShaderPart` nodes. See https://castle-engine.io/x3d_implementation_shaders.php about these X3D nodes.
+
To do this in Pascal (setup the nodes in Pascal), see demo on https://github.com/castle-engine/castle-engine/tree/master/examples/shaders/shader_override[examples/shaders/shader_override] .
+
To do this in X3D (editing X3D file), see https://github.com/castle-engine/demo-models[our demo models], in particular https://github.com/castle-engine/demo-models/tree/master/shaders[shaders] subdirectory.
--
* Activate batching by cgeref:TCastleViewport.DynamicBatching[]. It works completely automatically by grouping rendered shapes that use the same material.

*Advice when to use*:

* This approach is most powerful and flexible, so *this is the approach we advice now, always*.

* This approach allows engine to take care of animations, physics, and other cool stuff for you.

* All http://cat-astrophe-games.com/[Cat-astrophe Games] 2D games ("Dragon Squash", https://michalis.xyz/escape/["Escape from the Universe"], https://michalis.xyz/unholy/["The Unholy Society"]) were implemented using this approach.

=== Simple (imperative) option: Render using TDrawableImage

Use cgeref:TDrawableImage[] as your main way to draw. In this approach, you create cgeref:TDrawableImage[] instance for each image, and then draw it in overridden cgeref:TCastleUserInterface.Render[] method. This is the same approach as we use for our 2D user-interface rendering (various cgeref:TCastleUserInterface[] instances use it). *The main advantage of this approach is simplicity: you just draw 2D images.*

A similar approach is to draw your game using multiple cgeref:TCastleImageControl[] instances. cgeref:TCastleImageControl[] is a simple user-interface control that draws images, using `TDrawableImage` under the hood, exposing mostly the same features.

* Manual:
 ** link:view_events[Designing user interface and handling events (press, update) within the view] documents basic image display using cgeref:TCastleImageControl[].
 ** link:user_interface[User Interface].
 ** link:ui_custom_drawn[Custom drawn 2D controls] shows the "core" of this approach: new cgeref:TCastleUserInterface[] descendant with your own `Render` implementation, in which we call `TDrawableImage.Draw`.
* API reference: cgeref:TDrawableImage[].
* You can render sprites using the appropriate cgeref:TDrawableImage.Draw[] overload (where you specify which part of the source image to render).
+
WARNING: There's also a class `TSprite` (it uses `TDrawableImage` underneath), but it is _deprecated_ now, please don't use it.
* To render pixel-art, set cgeref:TDrawableImage.SmoothScaling[] to `false`.
* Besides cgeref:TDrawableImage[] there are also simple drawing helpers like cgeref:DrawRectangle[] that are also simple to use.
* To have fixed resolution (regardless of the actual window size in pixels), use link:manual_castle_settings.php#section_ui_scaling[UI scaling]. However, while it scales correctly all the existing cgeref:TCastleUserInterface[] instances, you will need to put some additional work to make UI scaling affect your custom cgeref:TCastleUserInterface[] descendant. This is documented at the bottom of link:ui_custom_drawn[Advanced: custom drawn 2D controls] -- basically, look at your `ScreenRect` and scale all coordinates by `UIScale` before passing them to `TDrawableImage`. So the scaling is _not_ hidden from you in this case -- you get the information you need, but you need to put some code to make it happen correctly.
+
To have the scaling automatically applied, you can use cgeref:TCastleImageControl[] instead of directly drawing with `TDrawableImage`. cgeref:TCastleImageControl[] is an UI control that wraps `TDrawableImage` underneath, and allows to control the image like a normal UI control: with anchors, automatically applied scaling and so on.

* To use custom shader, set cgeref:TDrawableImage.CustomShader[] or cgeref:TCastleImageControl.CustomShader[]. Demo in https://github.com/castle-engine/castle-engine/tree/master/examples/images_videos/image_render_custom_shader[examples/images_videos/image_render_custom_shader].
* You can use batching by cgeref:TDrawableImage.BatchingBegin[] and cgeref:TDrawableImage.BatchingEnd[]. It works completely automatically by grouping rendering the same image many times into one draw call.

*Advice when to use*: This approach is very easy to start. You have relatively small API to learn. You just learn how to use `TDrawableImage`, and you draw inside your own `TMyControl.Render` however you like. *If all you really want is a flexible API to draw images -- this is it.*

== Why there are 2 approaches to render 2D images/sprites

Because they are both useful :)

* Drawing using TDrawableImage is imperative.
* Settings things up using TCastleScene is declarative.

The _declarative_ approach is more powerful (the engine can do automatically a lot of more stuff for you, this way).

The _imperative_ stuff is simpler to use, and enough for simple use-cases. I wondered about removing this approach, but it seems many people like it, and it _is_ enough for many use-cases.

== Can these methods be combined, to render using TDrawableImage within TCastleScene?

I plan to enable rendering using TDrawableImage into a TCastleScene one day. Then you could render user interface into TCastleScene, rotate this TCastleScene, and have easy user-interface in 3D. This is part of link:roadmap[] .
