# How to render 2D games with images and sprites
include::common.adoc[]

cgeimg::float[platformer.png|Platformer]

== How to render 2D things

WARNING: This page compares 2 possible approaches to 2D rendering in CGE. This page is really *not* a good introduction into "making 2D games in CGE". For such introduction, instead follow the manual from the beginning, in particular link:viewport_and_scenes[learn about viewports, scenes] and link:viewport_2d[how to use them for 2D].

=== Full-featured option: Render using a viewport

Use cgeref:TCastleViewport[]. Add cgeref:TCastleViewport[] control to the window, and inside it draw things by creating cgeref:TCastleTransform[] descendants (like cgeref:TCastleScene[], cgeref:TCastleImageTransform[], cgeref:TCastlePlane[]).

You should call `TCastleViewport.Setup2D` on the viewport to easily make it suitable for 2D games, and call `TCastleScene.Setup2D` to easily make it suitable for 2D games. When using https://castle-engine.io/manual_editor.php[CGE editor], it already has in the menu components _"Viewport (2D)"_ and _"Scene (Optimal Blending for 2D Models)"_.

* Manual:
 ** link:viewport_and_scenes[Viewport with scenes, camera, navigation] introduces the cgeref:TCastleScene[].
 ** The cgeref:TCastleScene[] is incredibly versatile. You can load game models from files. E.g. Spine animations, Blender models etc. You can play animations. Everything described in link:viewport_and_scenes[viewport and scenes] works.
 ** Using cgeref:TCastleViewport[] for 2D is documented on link:viewport_2d[Viewport 2D].
 ** link:physics[Physics] shows how to use physics with it.
* The engine template "2D game" and `physics/physics_2d_game_sopwith/` shows this approach.
* The important API reference links: cgeref:TCastleScene[], cgeref:TCastleSceneCore[], cgeref:TCastleViewport[].
* To construct your own scene (not loaded from external file), you need to create a graph of X3D nodes. Various examples showing it are around the engine, the simpler is http://castle-engine.io/x3d_implementation_geometry2d.php . It instantiates a `TRectangle2DNode`. One could instead instantiate also `TIndexedFaceSetNode` which represents a free mesh, with custom texture coordinates and anything else you may need.
* To render sprites you can link:sprite_sheets[load sprite sheets from Castle Game Engine, Starling or Cocos2d formats to TCastleScene]. You can play it's animation just like any other scene (use `Scene.PlayAnimation` method, test with view3dscene panel "Animations").
+
If you want to do it manually, you can also construct your own `TIndexedFaceSetNode` instances and change texture coordinates.

* To render pixel-art, set texture filtering to "nearest". It's easiest to do this by setting `Scene.RenderOptions.MagnificationFilter := magNearest`. Alternatively, you could control this on a particular shape using `TTexturePropertiesNode`, links on http://castle-engine.io/x3d_implementation_texturing.php .
* You can load image as cgeref:TCastleImageTransform[] (more advised) or cgeref:TCastleScene[]. See link:using_images[using images].
* To have reliable field of view (regardless of the window size in pixels, regardless of UI scaling, regardless of viewport size), set cgeref:TCastleOrthographic.Width[Camera.Orthographic.Width] or cgeref:TCastleOrthographic.Height[Camera.Orthographic.Height] to non-zero. We advise this, this is usually most natural to control viewport field of view reliably. If you create a 2D viewport in editor, we actually initialize cgeref:TCastleOrthographic.Width[Camera.Orthographic.Width] to `1000` now.
+
If both cgeref:TCastleOrthographic.Width[Camera.Orthographic.Width] and cgeref:TCastleOrthographic.Height[Camera.Orthographic.Height] are zero then viewport field of view follows window size (adjusted by UI scaling). This is not advised. It means you will have to take more care to display proper content in all cases, in all allowed viewport sizes, window sizes etc.
+
See the _"2D game"_ new project template for example.
//+
// This is true burt confusing in light of above.
//You can also use link:manual_castle_settings.php#section_ui_scaling[UI scaling] to just make cgeref:TCastleViewport[] have the same width or height, regardless of the actual window size. All the scaling is completely hidden from you, inside cgeref:TCastleViewport[] you just work in your preferred coordinates.

* You can use physics in this approach (see example `physics/physics_2d_game_sopwith/`).
* You can mix 2D and 3D freely. The `TCastleViewport.Camera` defines projection settings and controls camera. The orthographic camera, `TCastleViewport.Camera.Orthoraphic`, is usually what you want for 2D games. Note that you can insert a cgeref:TCastleScene[] with 3D content to cgeref:TCastleViewport[].
* To use custom shaders, use X3D shader nodes.
+
--
- You can _override_ standard engine shaders using `ComposedShader` and `ShaderPart` nodes. See https://castle-engine.io/x3d_implementation_shaders.php about these X3D nodes.
+
To do this in Pascal (setup the nodes in Pascal), see demo on https://github.com/castle-engine/castle-engine/tree/master/examples/viewport_and_scenes/shader_override[examples/viewport_and_scenes/shader_override] .
+
To do this in X3D (editing X3D file), see https://github.com/castle-engine/demo-models[our demo models], in particular https://github.com/castle-engine/demo-models/tree/master/shaders[shaders] subdirectory.

- You can _add shader effects_ (to extend existing rendering) using `Effect` and `EffectPart` nodes. See https://castle-engine.io/compositing_shaders.php for documentation of these nodes.
+
To do this in Pascal (setup the nodes in Pascal), see demo on https://github.com/castle-engine/castle-engine/tree/master/examples/viewport_and_scenes/shader_effects[examples/viewport_and_scenes/shader_effects] .
+
To do this in X3D (editing X3D file), see https://github.com/castle-engine/demo-models[our demo models], in particular https://github.com/castle-engine/demo-models/tree/master/compositing_shaders[compositing_shaders] subdirectory.
--

*Advice when to use*:

* This approach is extremely versatile, so *this is the approach I advice if you plan to draw something more than images*.
* This approach is also easy, if you mostly load 2D models from existing files (Spine JSON, X3D exported from Blender or sprite-sheet-to-x3d). But it is a little more work to construct your own X3D graph -- as there are simply a lot of X3D nodes that you can use. But it pays off in my experience, you really can do everything. Our http://cat-astrophe-games.com/[Cat-astrophe Games] games ("Dragon Squash", "Escape from the Universe", http://store.steampowered.com/app/746750/The_Unholy_Society/["The Unholy Society"]) are all implemented using this approach.
* This approach allows engine to take care of animations, physics, and other cool stuff for you.

=== Simple (imperative) option: Render using TDrawableImage

Use `TDrawableImage` as your main way to draw. In this approach, you create `TDrawableImage` instance for each image, and then draw it in overridden `TCastleUserInterface.Render` method. This is the same approach as we use for our user-interface rendering (various `TCastleUserInterface` instances). *The main advantage of this approach is simplicity: you just draw 2D images.*

A similar approach is to draw your game using multiple cgeref:TCastleImageControl[] instances. `TCastleImageControl` is a simple user-interface control that draws images, using `TDrawableImage` under the hood, exposing mostly the same features.

* Manual:
 ** link:view_events[Designing user interface and handling events (press, update) within the view] documents basic image display using cgeref:TCastleImageControl[].
 ** link:user_interface[User Interface].
 ** link:manual_2d_ui_custom_drawn.php[Custom drawn 2D controls] shows the "core" of this approach: new `TCastleUserInterface` descendant with your own `Render` implementation, in which we call `TDrawableImage.Draw`.
* API reference: cgeref:TDrawableImage[].
* You can render sprites using the appropriate `TDrawableImage.Draw` overload (where you specify which part of the source image to render). Or use ready class `TSprite` (it uses `TDrawableImage` underneath).
* To render pixel-art, set `TDrawableImage.SmoothScaling` to `false`.
* Numerous engine demos use `TDrawableImage`. Example `isometric_game` draws simple map using it.
* Besides `TDrawableImage` and `TSprite`, there are also simple drawing helpers like `DrawRectangle`.
* To have fixed resolution (regardless of the actual window size in pixels), use link:manual_castle_settings.php#section_ui_scaling[UI scaling]. However, while it scales correctly all the existing `TCastleUserInterface` instances, you will need to put some additional work to make UI scaling affect your custom `TCastleUserInterface` descendant. This is documented at the bottom of http://castle-engine.io/manual_2d_ui_custom_drawn.php[] -- basically, look at your `ScreenRect` and scale all coordinates by `UIScale` before passing them to `TDrawableImage`. So the scaling is _not_ hidden from you in this case -- you get the information you need, but you need to put some code to make it happen correctly.
+
To have the scaling automatically applied, you can use `TCastleImageControl` instead of directly drawing with `TDrawableImage`. `TCastleImageControl` is an UI control that wraps `TDrawableImage` underneath, and allows to control the image like a normal UI control: with anchors, automatically applied scaling and so on.

* To use custom shader, set `TDrawableImage.CustomShader` or `TCastleImageControl.CustomShader`. Demo in `examples/images_videos/image_render_custom_shader.lpr`.

*Advice when to use*: This approach is very easy to start. You have relatively small API to learn. You just learn how to use `TDrawableImage`, and you draw inside your own `TMyControl.Render` however you like. *If all you really want is a flexible API to draw images -- this is it.*

== Why there are 2 approaches to render 2D images/sprites

Because they are both useful :)

* Drawing using TDrawableImage is imperative.
* Settings things up using TCastleScene is declarative.

The _declarative_ approach is more powerful (the engine can do automatically a lot of more stuff for you, this way).

The _imperative_ stuff is simpler to use, and enough for simple use-cases. I wondered about removing this approach, but it seems many people like it, and it _is_ enough for many use-cases.

== Can these methods be combined, to render using TDrawableImage within TCastleScene?

I plan to enable rendering using TDrawableImage into a TCastleScene one day. Then you could render user interface into TCastleScene, rotate this TCastleScene, and have easy user-interface in 3D. This is part of link:roadmap[] .
