:doctype: book
:sectnums:
:source-highlighter: coderay
:toc: left

You can read how the set the environment for deploying to link:pass:[Android][], and for deploying to link:pass:[iOS][] devices on separate pages. This page describes the process when you want to use a single Mac computer to do both.

*Note: This document was not updated since FPC 3.0.4. Some steps may be easier now with later FPC, and definitely things are easier with link:pass:[fpcupdeluxe][]. We hope that this information is useful, but you should not follow it literally.*

The main problem comes from the current state of the stable FPC release, when there are official FPC packages for macOS development (version 3.0.4) and cross compiler to iOS (version 3.0.5). And you have to manually compile the cross compiler for Android using FPC version 3.0.0.

We hope this process will simplify a lot after FPC releases a new stable version (3.1.1?). You can also use link:pass:[fpcupdeluxe][] that does everything for you.

= Compile Android cross compiler

Cross compiler is not distributed as an official package, so you need to compile it yourself. And you need FPC 3.0.0 for this (i.e. not 3.0.4) together with FPC sources for version 3.0.4.

. Download and install https://sourceforge.net/projects/freepascal/files/Mac%20OS%20X/3.0.0/[FPC 3.0.0 for macOS]
`fpc-3.0.0.intel-macosx.dmg`
. Download and install https://sourceforge.net/projects/lazarus/files/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.8.0/[FPC 3.0.4 sources]
`fpc-src-3.0.4-macosx.dmg`. You have to do this step when you want to run Lazarus on your computer anyway, so I recommend to download the sources from the official Lazarus distribution.
. Install Android Studio with _"Android 6.0 (Marshmallow) - API 23"_, _"Android SDK Build-tools"_ version 23.0.2 and NDK as described on our link:pass:[Android][] page.

Before compiling the cross compiler, you need to add Android binutils to your $PATH. If you also plan to use our link:pass:[Build Tool][], your `~/.bash_profile` should look like:

----
export PATH="$HOME/MyProjects/castle-engine/tools/build-tool:$HOME/Library/Android/sdk/platform-tools:$HOME/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin:$PATH"
export CASTLE_ENGINE_PATH=$HOME/MyProjects/castle-engine/
export ANDROID_HOME=$HOME/Library/Android/sdk
export ANDROID_NDK_HOME=$HOME/Library/Android/sdk/ndk-bundle
----

Let's create the cross compiler as described on our link:Android#fpc-for-android[Android] page or http://wiki.freepascal.org/Android[Lazarus wiki]. If you used the above packages and installed them to their default locations, following two lines should do it.

----
cd /usr/local/share/fpcsrc
sudo make clean crossall crossinstall OS_TARGET=android CPU_TARGET=arm CROSSOPT="-Cfvfpv3" INSTALL_PREFIX=$HOME/fpc_android
----

= Install FPC 3.0.4

. Download and install https://sourceforge.net/projects/freepascal/files/Mac%20OS%20X/3.0.4/[FPC 3.0.4 for macOS]
`fpc-3.0.4.intel-macosx.dmg`
. Download and install https://sourceforge.net/projects/freepascal/files/Mac%20OS%20X/3.0.4/[FPC 3.0.5 cross iOS for macOS]
`fpc-3.0.5.intel-macosx.cross.ios.dmg`

You can also install https://sourceforge.net/projects/lazarus/files/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.8.0/[Lazarus] at this moment.

= Put compilers together

Right now, you can compile to iOS without problems, we just need to "install" our compiled Android cross compiler.

Navigate to `/usr/local/lib/fpc`. The official packages install there, so you should find the following directory structure there:

----
3.0.0   (not interesting for us anymore, can be deleted later)
3.0.4   (main 3.0.4 compiler with units for i386 and x86_64)
  +-- units/
        +-- i386-darwin/
        +-- x86_64-darwin/
  +-- fpmkinst/  (same structure as units/)
  +-- ppc386, ppcx64
3.0.5   (special version for compiling to iOS)
  +-- units/
        +-- aarch64-darwin/
        +-- arm-darwin/
        +-- i386-iphonesim/
        +-- x86_64-iphonesim/
  +-- fpmkinst/  (same structure as units/)
  +-- ppc386, ppcx64, ppcarm, ppca64
----

To have everything organised, I recommend to copy our Android cross compiler into this structure, under 3.0.4 directory.

Navigate to `~/fpc_android/lib/fpc/3.0.4` and copy all contents to `/usr/local/lib/fpc/3.0.4`. It means:

* copy `~/fpc_android/lib/fpc/3.0.4/fpmkinst/arm-android` to `/usr/local/lib/fpc/3.0.4/fpmkinst/`
* copy `~/fpc_android/lib/fpc/3.0.4/units/arm-android` to `/usr/local/lib/fpc/3.0.4/units/`
* copy `~/fpc_android/lib/fpc/3.0.4/ppcrossarm` to `/usr/local/lib/fpc/3.0.4/`

Unfortunately, it's not enough. When running `fpc -Parm` command to run ARM compiler, FPC automatically uses the ppcarm version for iOS under version 3.0.5. Let's prepare the link to run our ARM compiler too.

----
cd /usr/local/bin
sudo ln -s ../lib/fpc/3.0.4/ppcrossarm ppcarm-3.0.4
----

To verify, you can run:

 $ ls -l /usr/local/bin/ppc*
 lrwxr-xr-x  1 root  (...) /usr/local/bin/ppc386 -> ../lib/fpc/3.0.4/ppc386
 lrwxr-xr-x  1 root  (...) /usr/local/bin/ppc386-3.0.5 -> ../lib/fpc/3.0.5/ppc386
 lrwxr-xr-x  1 root  (...) /usr/local/bin/ppca64 -> ../lib/fpc/3.0.5/ppca64
 lrwxr-xr-x  1 root  (...) /usr/local/bin/ppcarm -> ../lib/fpc/3.0.5/ppcarm
 lrwxr-xr-x  1 root  (...) /usr/local/bin/ppcarm-3.0.4 -> ../lib/fpc/3.0.4/ppcrossarm
 lrwxr-xr-x  1 root  (...) /usr/local/bin/ppcx64 -> ../lib/fpc/3.0.4/ppcx64
 lrwxr-xr-x  1 root  (...) /usr/local/bin/ppcx64-3.0.5 -> ../lib/fpc/3.0.5/ppcx64

Another solution would be to unlink ppcarm from version 3.0.5 and link it to our Android compiler, but I decided not to touch the official distribution.

= Add Android NDK paths to fpc.cfg

The last configuration step is to add the path to Android NDK libraries to your fpc.cfg. The default location of this file on macOS is `/etc/fpc.cfg`. I recommend to edit it and insert following lines, for example under the section with Xcode libraries _(-Fl/Applications/Xcode.app/...)_:

----
#ifdef android
#ifdef cpuarm
-Fl/users/your_user_name/library/Android/sdk/ndk-bundle/platforms/android-23/arch-arm/usr/lib
#endif
#ifdef cpu386
-Fl/users/your_user_name/library/Android/sdk/ndk-bundle/platforms/android-23/arch-x86/usr/lib
#endif
#endif
----

= Running the Build Tool

As we have this confusion about `ppcarm` version, we have to tell the link:pass:[Build Tool][] we need to use FPC version 3.0.4 when compiling to Android. Use the `--compiler-option` command line parameter. So, for example, the command line can be:

----
# Android
castle-engine package --os=android --cpu=arm --compiler-option=-V3.0.4
----

For iOS, nothing special is needed:

----
# iOS
castle-engine package --target=ios
----
