# Model formats
include::common.adoc[]
:description: Supported 3D and 2D model formats in Castle Game Engine.

The following 3D and 2D model formats are supported by _Castle Game Engine_.
You can load and display them link:viewport_and_scenes[using `TCastleScene` in a viewport].
You can also link:castle-model-viewer[open them in Castle Model Viewer].

== Best formats (recommended and with great support)

=== glTF 2.0

An efficient, modern format for animated 3D and 2D models.

glTF is supported by a lot of tools, in particular link:blender[Blender has a full-featured exporter to glTF built-in]. We are dedicated to perfect glTF support, with all the features and efficiency.

link:gltf[Details about glTF support in Castle Game Engine].

=== IFC

link:ifc[IFC] (Industry Foundation Classes) is a standard format for BIM (Building Information Modeling) data. It is supported by many tools in the industry, like https://www.freecad.org/[FreeCAD], https://bonsaibim.org/[BonsaiBIM], _Revit_, _ArchiCAD_.

=== Spine JSON

http://esotericsoftware.com/[Spine] is a powerful program
for 2D game skeletal animations.

https://castle-engine.io/spine[We have a big support for Spine JSON features],
and our friendly game studio http://cat-astrophe-games.com/[Cat-astrophe Games]
is using Spine for all 2D games.

=== Sprite sheets

You can load animations as _sprite sheets_, defined using various formats:

. _Castle Game Engine_ format (extension `.castle-sprite-sheet`), created by link:manual_editor.php[sprite sheet editor inside the CGE editor].

. _Starling (XML) format_ (traditionally with `.xml` extension, in CGE we require you rename them to `.starling-xml`).

. _Cocos2d format_ (traditionally with `.plist` extension, in CGE we advise (but do not require yet) to use `.cocos2d-plist`).

See the https://castle-engine.io/sprite_sheets[sprite sheets documentation].

=== X3D and VRML

link:x3d[X3D and VRML] is a flexible
and powerful format for 3D models and a basis of our scene graph.

The following extensions are recognized:

* X3D in classic and XML encoding:
  `.x3d`, `.x3dz`, `.x3d.gz`,
  `.x3dv`, `.x3dvz`, `.x3dv.gz`

* VRML 1.0 and 2.0:
  `.wrl`, `.wrz` and `.wrl.gz`.

// Almost complete VRML 1.0 support is done.
// VRML 2.0 (aka VRML 97) and X3D support is also quite advanced,
// a lot of nodes and features are implemented (including
// advanced texturing and GLSL shaders,
// PROTO and EXTERNPROTO support,
// events mechanism with routes, sensors and interpolators).

// Among things that work are embedded textures,
// semi-transparent materials and semi-transparent textures,
// automatic normals smoothing (based on creaseAngle),
// triangulating non-convex faces, understanding camera nodes,
// WWWInline handling, text rendering and more.

We have a great support for X3D and VRML,
and handle rendering, animation, interaction, scripts, shaders
and more features of these formats.
An entire section of this website,
link:x3d[Scene Graph: X3D nodes],
documents all the features we support (from the X3D and VRML standard,
and many of our own extensions).

Note that X3D has a lot of features, and most exporters do not allow to configure everything possible in X3D.
But you can use `Inline` node to include one file (X3D, glTF or any other that CGE can handle)
within another X3D file, and you can simply write some X3D content by hand.
That's good for adding scripts to 3D data, and generally adding
stuff that is uncomfortable (or impossible) to design in your 3D modeller.
See e.g. the
https://github.com/castle-engine/castle-engine/blob/master/examples/3d_games/explore_impressive_castle/data/level/terrain_multi_texture.x3dv[terrain_multi_texture.x3dv example (X3D file from examples/3d_games/explore_impressive_castle)].

// If your authoring software
// can export to X3D, this is the format you should probably use.

== Other formats (supported but not recommended)

=== MD3

*MD3* is a 3D model format used by https://en.wikipedia.org/wiki/Id_Tech_3[id Tech 3] engine
and games based on it, like
https://en.wikipedia.org/wiki/Quake_III_Arena[Quake 3] and http://tremulous.net/[Tremulous].

We have advanced support for this format, including skins and animations.
More information in a link:md3[dedicated page about MD3 support].

=== Simple images

You can load image as a scene too. That is, you can load a simple PNG, JPG etc. file using `TCastleScene.Load` method. It will create a rectangle (which you can use as 3D or 2D object) using this image as a texture, with size adjusted to the image size.

Or, even better, use a dedicated cgeref:TCastleImageTransform[] that is a link:viewport_and_scenes[transformation dedicated to loading the image], it has helpful properties to easily adjust image size, repeat, pivot etc.

See also https://castle-engine.io/using_images[image loading documentation].

=== Animation through a series of static models

*Animation through a series of static models like `xxx000.obj`,
`xxx001.obj`, `xxx002.obj`...*

This is useful if you have files named like:

----
xxx001.obj
xxx002.obj
xxx003.obj
...
----

You can load such animation from a sequence of files using the URL `xxx@counter(3).obj`. It's exactly how you can load link:x3d_implementation_texturing_extensions.php#section_ext_movie_from_image_sequence[a movie from a sequence of images]. See https://github.com/castle-engine/demo-models/tree/master/animation/blender_skinned_animation/not_recommended_formats/wavefront_obj_animation[demo-models/.../wavefront_obj_animation] for an example, you would load them by `skinned_anim_@counter(6).obj`.

It's not an efficient way to store the animation in a file (or to load it). It is much better to export to X3D or glTF animation, if you can. But it may be useful when you have no other option to export.

Blender exporter to _Wavefront OBJ_ with _"Animation"_ checkbox generates such animation. Hint: uncheck _"Write Normals"_ and check _"Keep Vertex Order"_ in the exporting dialog box, to make sure models are "structurally equal" which allows CGE to merge the animation nicely (even produce more intermediate animation frames, if needed). This also means that CGE will recalculate normals by itself (unfortunately this isn't always desired, because Blender doesn't pass the creaseAngle information to CGE, so CGE cannot smooth the normals as in Blender -- it doesn't know when it should).

The animation is played and smoothed following the same logic as link:castle_animation_frames[castle-anim-frames] format. In a way, using URL `xxx@counter(4).obj` is just a shortcut for creating a `xxx.castle-anim-frames` file that would list the appropriate static frames using XML elements.

=== Collada

*http://www.khronos.org/collada/[Collada]*
(`.dae` extension).
We support a lot of Collada features -- geometry with materials,
textures, cameras, lights. Tested on many Collada examples,
like http://collada.org/owl/[Collada Test Model Bank]
and Collada models exported from various http://www.blender.org/[Blender]
versions.
All modern Collada versions (1.3, 1.4, 1.5) are handled.

Animations in Collada files are not handled yet.
If you need animations, we advise to use glTF instead.
glTF is newer and has similar feature set.
https://github.com/KhronosGroup/COLLADA2GLTF[Khronos provides a converter
from Collada to glTF].

=== OpenInventor

https://en.wikipedia.org/wiki/Open_Inventor[*OpenInventor*]
1.0 ASCII files (`.iv` extension) are handled.
Inventor 1.0 and VRML 1.0 are very similar
formats, we also handle some additional Inventor-specific nodes.

=== 3DS

*3d Studio 3DS format*. We support most important things:
meshes, cameras, materials, textures.

=== Wavefront OBJ

*Wavefront OBJ files*. We support most important things:
geometry (with texture coords, normal vectors), materials
(colors, opacity, texture filenames).

=== STL

*STL (Standard Triangle Language, aka STereoLithography)*.
https://en.wikipedia.org/wiki/STL_%28file_format%29[STL] is a simple
popular 3D format used in 3D printing.
We support both ASCII and binary formats.

=== Videoscape GEO

*http://paulbourke.net/dataformats/geo/[Videoscape GEO]*
(`.geo` extension).
Very basic support for this very old 3D format.

=== Deprecated: Castle Animation Frames (castle-anim-frames) format

link:castle_animation_frames[Castle Animation Frames
(castle-anim-frames) format],
formerly known as `kanim`.

This is a simple format for animations, which we used in the past
to link:blender[export animated models from Blender].
It supported animating of _everything_ in Blender (transformations, skin,
shape keys, materials, particles, physics...), although it is somewhat
memory-hungry.

We advise now using glTF for all your animation needs.

== Other formats (not supported by engine core, but can be used with additional tools)

=== SVG

You can https://create3000.github.io/x_ite/laboratory/x3d-file-converter[use X_ITE converter to convert SVG to X3D] and then read X3D inside our engine, as a scalable geometry. There is also https://www.npmjs.com/package/x3d-tidy[a command-line converter x3d-tidy using the same X_ITE under the hood].

Note that in the generated X3D file, all objects will be placed at the same depth, Z = 0, at least right now. You may have to fix it to avoid Z-fighting in case SVG layers overlap. For simple cases, it is possible to do this by just manually editing the X3D file in any text editor.

For more information see:

* https://castle-engine.io/wp/2023/02/25/convert-svg-to-x3d-using-x_ite-to-display-svg-as-geometry-in-castle-game-engine/[News post about it]

* https://github.com/castle-engine/demo-models/tree/master/svg[demo-models/svg with an example SVG and X3D files documenting the process].

Of course you can also convert SVG to a raster image (like PNG) using e.g. https://inkscape.org/[Inkscape export options].

=== FBX

FBX is a https://en.wikipedia.org/wiki/FBX[proprietary format from Autodesk]. As such it has good support in Autodesk software like link:3dsmax[3ds Max] and link:maya[Maya].

If you have FBX models, we recommend converting them to glTF using https://github.com/facebookincubator/FBX2glTF[FBX2glTF]. It's a simple command-line tool, just call it with the FBX model file name:

----
FBX2glTF model.fbx
----

After the export, the `modelname_out` subfolder will appear with the exported model. The conversion result can be easily compared using e.g. link:castle-model-viewer[Castle Model Viewer].

_Note: We do not recommend using FBX in your workflow._
// Being a proprietary format, it means that even official specification of FBX is not available to us. All software that supports FBX either paid royalties to Autodesk for their documentaion and proprietary FBX SDK, or reverse-engineered the format. In terms of features, both glTF and X3D rival FBX.
We believe that _open standards_, like <<best,glTF>> and <<best,X3D>> are a better way to innovate. See e.g. https://castle-engine.io/gic2022[Michalis GIC 2022 presentation slides].
