# Mountains Of Fire
include::common.adoc[]
:description: Mountains Of Fire - a split-screen cooperative game made with Castle Game Engine.

== Introduction

// mountains_of_fire_screen_5.png - unused

// _Mountains of Fire_ is a small 3D game. It features
This split-screen game shows the 3D world from two different perspectives:

. a worm, swimming in _hot_ lava, and
. a human, _carefully_ walking over the rocky surface.

Together, they cooperate to reach a safe place within the mountains flooded with lava. The game can be played by two players, or by a single player controlling both human and sandworm simultaneously. The controls were designed to be reachable by a single player.

The game is open-source, completely free to download and play. Try it now!

cgeimg::block[
  mountains_of_fire_screen_0.png|Mountains Of Fire - game screen 1,
  mountains_of_fire_screen_1.png|Mountains Of Fire - game screen 2,
  //mountains_of_fire_screen_2.png|Mountains Of Fire - game screen 3,
  mountains_of_fire_screen_3.png|Mountains Of Fire - game screen 4,
  mountains_of_fire_screen_4.png|Mountains Of Fire - game screen 5
]

== Download

cge::download-application[
  1.1.0,
  snapshot,
  castle-engine,
  mountains-of-fire,
  mountains_of_fire,
    win64-x86_64;
    linux-x86_64
]

== Controls and hints how to play

. Human views the world in 1st person. It walks over the terrain. In right-handed mode, human view is the right one.
+
Human is controlled only with mouse. Move mouse to look around. Click mouse left button to start/stop moving forward (no need to hold the button pressed), Click mouse right button to start/stop moving backward (no need to hold the button pressed).
+
Human is hurt by hot lava. Stand on a neutral ground (rocks) to regenerate, or very close to the worm when it freezes the lava (on blueish fluid).
+
When the human dies, game ends.

. Worm views the world from the top. It can swim in lava. In right-handed mode, worm view is the left one.
+
Move the worm with AWSD.
+
Worm freezes lava into a water that is not harmful for player. Worm is hurt when it stays stationary for too long, as the heat is too much even for a sandworm. You have to move the worm to regenerate.
+
When the worm dies, human can still try to continue the game.

Hints:

* Worm is visible in both views, even when it's obscured by a wall etc. If you're lost, human can look around, and see where the worm is.

Miscellaneous keys:

* F5 takes a screenshot.
* Escape exit.

== Command-line options

* `--left-handed`
+
Run the game swapping the split screen order. This is useful if the mouse is on the left of the keyboard, then you want the left screen part to show human view (as human is controlled by mouse).

* link:cli_options_window[Usual window size and fullscreen options]. By default we start in fullscreen.

* link:openal#_command_line_options_that_control_the_sound_output[Usual sound options]. For example `--no-sound`.

* `--debug-log`, `--debug-speed`

== License

The game code and some of the data are licensed on GNU GPL (version >= 2). The rest of the game data is licensed on Creative Commons (various versions, see AUTHORS.txt files in the source code for details). The underlying Castle Game Engine is licensed on more permissive link:license[GNU LGPL with static linking exception].

The game was originally developed during the weekend gamejam (https://www.facebook.com/tsgcompo[TSG compo]) on 21-22nd of June 2014. Design, programming, modeling by Michalis Kamburelis.
