# New Features in Castle Game Engine 7.0
include::common.adoc[]

== New Features

This page documents Castle Game Engine 7.0 new features (since the last 6.4 release). It's a work in progress -- as we work on making CGE 7.0 ready for release.

* https://castle-engine.io/manual_editor.php[Castle Game Engine Editor application!]
 ** Run it by simply executing "castle-editor" binary in the "bin/" subdirectory of our release zip.
 ** It comes with 4 templates for new projects: empty, 3D model viewer, 2D game, 3D FPS game. These showcase nicely editor possibilities and were designed as a good starting point for your applications.
 ** Editor allows to visually design TCastleUserInterface (like TCastleButton, TCastleLabel) and TCastleTransform (like TCastleScene) hierarchies.
 ** Editor also manages (creates, compiles) Castle Game Engine projects, using our https://github.com/castle-engine/castle-engine/wiki/Build-Tool[build tool] underneath.
 ** Integrated with our tools (runs view3dscene, castle-view-image etc. when double-clicking), can preview data (models, images, sounds).
 ** Runs a configured FPC/Lazarus (in preferences).
* glTF 2.0 full support and realistic rendering upgrades.
 ** Including _Physically Based Rendering_ materials, unlit materials and textures. This is supported in both glTF and X3D formats. The X3D nodes follow new X3D 4.0 standard.
 ** Animation of transformations and skin.
 ** Metadata support (e.g. from Blender custom properties), can also be used to set colliders.
 ** See https://castle-engine.io/creating_data_model_formats.php for details of glTF 2.0 support.
 ** See numerous news for details: https://castle-engine.io/wp/2020/04/25/huge-optimizations-of-gltf-animations-pool-of-scenes-for-fps-game-limited-pbr-specular-glossiness-support/[1], https://castle-engine.io/wp/2020/04/19/lots-of-gltf-work-new-x3d-extensions-and-conversion-improvements/[2], https://castle-engine.io/wp/2020/04/11/fun-with-sketchfab-plugin-in-blender-testing-gltf-performance/[3],  https://castle-engine.io/wp/2020/04/11/testing-gltf-with-models-from-sketchfab-improved-per-vertex-rendering-from-gltf/[4], https://castle-engine.io/wp/2020/04/01/gltf-skinned-animation-in-castle-game-engine/[5], https://castle-engine.io/wp/2020/03/22/blender-exporters-upgrades-and-fixes-gltf-unlit-support-castle-anim-frames-improvements-loading-a-series-of-models-for-animation/[6], https://castle-engine.io/wp/2020/06/11/reading-punctual-lights-from-gltf/[lights].
 ** See https://castle-engine.io/wp/2020/03/07/physically-based-rendering-and-lots-of-other-lighting-materials-upgrades-in-castle-game-engine-and-x3d-4-0/[news specific about PBR (in glTF and X3D v4)]
 ** https://castle-engine.io/manual_gamma_correction.php[Gamma Correction and Tone Mapping].
* Nintendo Switch full support. See https://github.com/castle-engine/castle-engine/wiki/Nintendo-Switch
* Much better API for viewports and cameras.
 ** To display `TCastleScene`/`TCastleTransform` hierarchy, use `TCastleViewport`, always. It is a normal user interface control, you can set it's size/position as any other UI control.
 ** The concept of _camera_ (where are you looking at) and _navigation_ (whether we handle some keys/mouse to move the camera) was split. `TCastleViewport.Camera` is always created, and corresponds 1-to-1 to the parent viewport. `TCastleViewport.Navigation` is optional, you can explicitly create an instance of `TCastleExamineNavigation` or `TCastleWalkNavigation` and assign them there.
 ** Auto-detection of camera is by default off. This way you can reliably use `+Viewport.Camera.SetView(...)+` or `+Viewport.Camera.Position := ...+`, without worrying that some auto-detection will override them. Use `Viewport.AutoCamera := true` to explicitly request this auto-detection.
 ** Auto-detection of navigation is by default off. This way you can reliably set `+Viewport.Navigation := ...+` (or leave it `nil` deliberately) without worrying that some auto-detection will override it. Use `Viewport.AutoNavigation := true` to explicitly request this auto-detection.
 ** See https://castle-engine.io/wp/2019/12/29/last-refactor-before-cge-7-0-release-say-hello-to-tcastleviewport-and-tcastlewindowbase-say-goodbye-to-tcastlescenemanager-and-tcastlewindow/[news 1], https://castle-engine.io/wp/2019/11/19/huge-camera-and-navigation-improvements-thank-you-patrons/[news 2]. See https://github.com/castle-engine/castle-engine/blob/master/examples/3d_rendering_processing/view_3d_model_basic.lpr[view_3d_model_basic example].
* https://castle-engine.io/wp/2020/06/29/third-person-navigation-with-avatar-component-in-castle-game-engine/[Third-Person Navigation (with Avatar) component]
* https://castle-engine.io/wp/2020/07/19/asynchronous-non-blocking-downloading-using-tcastledownload-class-and-other-http-communication-features/[New TCastleDownload class, to make asynchronous (non-blocking) downloading, or even to implement full-featured asynchronous communication with a REST server]
* 2D games:
 ** Load sprite sheets and images to TCastleScene. See https://castle-engine.io/wp/2020/11/28/new-comfortable-way-of-using-sprite-sheets-and-images-in-viewports/[news], link:sprite_sheets[Sprite Sheets], link:using_images[Images].
 ** https://castle-engine.io/wp/2020/08/18/weighted-mesh-skinned-mesh-animation-in-spine/[Weighted mesh (skinned mesh animation) in Spine]
* Big user interface classes improvements.
 ** Easy functions to serialize / deserialize TCastleUserInterface and TCastleTransform hierarchies (see CastleComponentSerialize unit) as JSON files.
 ** https://castle-engine.io/manual_castle_settings.php[CastleSettings.xml file support] to easily define scaling and default font.
 ** New controls: TCastleCheckbox, TCastleDesign, TCastleHorizontalGroup, TCastleVerticalGroup.
 ** Float positions / sizes for everything.
 ** _All_ existing controls significantly reworked and improved. So many improvements to our user interface hierarchy happened that it's impossible to list it in short -- see news
https://castle-engine.io/wp/2019/02/17/new-user-interface-capabilities/[1],
https://castle-engine.io/wp/2018/11/26/november-engine-features-part-3-user-interface-classes-checkbox-refer-to-embedded-design/[2],
https://castle-engine.io/wp/2018/11/25/november-engine-features-part-2-tcastleuserinterface-borders-culling-clipping-events/[3],
https://castle-engine.io/wp/2018/11/24/november-engine-features-part-1-editor-anchors-9-slices-rulers-copy-paste-documentation/[4],
https://castle-engine.io/wp/2018/10/21/big-user-interface-and-editor-improvements/[5],
https://castle-engine.io/wp/2018/12/24/database-aware-demo-using-castle-game-engine-ui/[6],
https://castle-engine.io/wp/2018/04/22/engine-improvements-user-interface-horizontal-vertical-layout-groups-on-screen-keyboard-and-freetype-on-android-better-ui-scaling/[7].
* `castle-data:/` protocol (more advised than previous `ApplicationData` function). The "`data`" directory is documented https://castle-engine.io/manual_data_directory.php in a new manual page. It is also listed on a reworked manual page about networking, downloading and URLs https://castle-engine.io/manual_network.php.
* `TCastleTransformDesign` to refer to a designed `xxx.castle-transform` file, which can be used similar to Unity prefabs,
* `TCastleBehavior` to enhance `TCastleTransform` functionality by behaviors like `TCastleBillboard` or `TCastleSoundSource`. See `examples/creature_behaviors/`. See also link:castle_game_engine_for_unity_developers[Castle Game Engine for Unity developers].
* Optimizations and profiling features:
 ** Built-in simple profiler (TCastleProfiler, use through the Profiler singleton). See https://castle-engine.io/wp/2018/08/25/headlight-built-in-simple-profiler-more/
 ** Built-in frame profile (TCastleFrameProfiler)
 ** Integration with Nintendo profiler
 ** Large speedups, see news: https://castle-engine.io/wp/2019/10/13/numerous-optimizations-and-dynamic-batching/ .
 ** Dynamic batching now available.
 ** Loading optimizations (see https://castle-engine.io/wp/2019/12/15/engine-improvements-gtkglext-no-longer-used-new-tcastleinspectorcontrol-loading-optimizations-twosidedmaterial-node/[here]).
 ** Everything described in the updated optimization docs on https://castle-engine.io/manual_optimization.php
* Rendering:
 ** New screen effects API, you can now make screen effects over any UI control (just place it as child of https://castle-engine.io/apidoc-unstable/html/CastleScreenEffects.TCastleScreenEffects.html), and they are much friendlier to use. See https://castle-engine.io/wp/2018/07/29/new-screen-effects-api-and-demo-text-node-optimizations-multi-texture-modes-fixes/ . Also https://castle-engine.io/x3d_extensions_screen_effects.php[new GLSL screen-effects functions]. See also https://castle-engine.io/wp/2020/11/07/screen-space-reflections-effect-enhancements-to-glsl-api-for-effects/[news about screen-space reflections].
 ** Easy mirrors on flat surfaces (see https://castle-engine.io/wp/2018/10/08/simple-water-using-castle-game-engine/ )
 ** Aside from new _Physically-Based Rendering_ (using `PhysicalMaterial` in X3D), also unlit rendering (using `UnlitMaterial` in X3D) and Phong lighting model (using `Material` in X3D) got serious improvements. https://github.com/michaliskambi/x3d-tests/wiki/Why-is-UnlitMaterial-useful[Explicit node for unlit rendering makes some cases more natural]. https://github.com/michaliskambi/x3d-tests/wiki/X3D-version-4:-New-features-of-materials,-lights-and-textures[Improvements to Material allow to configure everything using separate textures naturally (diffuseTexture, specularTexture, ambientTexture etc.), and we add natural slot for occlusion maps].
 ** Shadow maps, clip planes available with OpenGLES renderer (this improves all platforms using OpenGLES by default: Android, iOS and Nintendo Switch).
 ** https://castle-engine.io/wp/2019/08/11/astc-texture-compression-progress-of-engine-delphi-compatibility/[ASTC (Texture Compression) Support]
 ** https://castle-engine.io/wp/2020/10/09/attach-objects-to-animated-bones-like-weapon-in-characters-hand-by-exposetransforms/[Easily attaching an object to an animated bones, by ExposeTransforms]
 ** https://castle-engine.io/wp/2020/11/07/render-options-configurable-in-editor/[TCastleScene.RenderOptions, configurable by editor too]
* Localization:
 ** Two methods, with demos: https://castle-engine.io/manual_text.php
 ** CastleLocalizationGetText allows to easily translate UI design (created e.g. using CGE editor), including generating template for translators to translate UI design.
 ** See https://castle-engine.io/wp/2019/07/21/localization-improvements-and-a-japanese-version-of-escape-from-the-universe/ and https://castle-engine.io/wp/2018/04/25/engine-improvements-localization/ .
* Animation features:
 ** Animation blending (https://castle-engine.io/wp/2018/03/21/animation-blending/)
 ** Many new features related to PlayAnimation. TPlayAnimationParameters allows to specify things like StopNotification callback, playing backward etc. (see https://castle-engine.io/wp/2018/04/21/engine-improvements-rejuvenated-playanimation-method-easily-play-animations-backward-with-blending-stop-notifications/ ). Additional methods like StopAnimation, ResetAnimationState.
 ** Ability to easily play simultaneous animations using TTimeSensorNode.Start/Stop.
 ** See https://castle-engine.io/wp/2019/06/22/many-animations-improvements-gltf-simultaneous-anims-view3dscene-panel-optimizations/
 ** Spine https://castle-engine.io/wp/2020/01/05/animating-by-mesh-deformation-in-spine-physics-spiral-of-death-avoidance-examples-and-manual-upgrades/[mesh deformation] animation
* Notable new examples:
 ** tiled/strategy_game_demo/ - Complete working strategy game, with maps designed using Tiled, working equally well with hexagonal/orthogonal/isometric maps (thanks to new Tiled API), user interface designed using Castle Game Engine Editor and TUIState. See also https://castle-engine.io/wp/2019/01/06/strategy-game-demo-using-cge-and-tiled/ , https://castle-engine.io/wp/2018/12/28/tiled-maps-improvements/ .
 ** tiled/map_viewer/ - Simple viewer for Tiled maps. You can pan and zoom maps, and load any Tiled map.
 ** headlight_test/ - Shows new `Viewport.Items.UseHeadlight` property.
 ** audio/play_sounds/ - Test mixing sounds.
 ** localization/gettext/ - Localization example, translating resourcestrings and UI designed in CGE editor.
 ** screen_effects_demo/ - New screen effects API demo.
 ** 3d_rendering_processing/anisotropic_filtering/ - Using anisotropic filtering.
 ** network/asynchronous_download/ - asynchronous, cross-platform downloading using TCastleDownload.
 ** network/remote_logging/ - remote logging, basis of communicating with REST server using TCastleDownload.
 ** third_person_camera/ - 3rd-person navigation (with avatar) demo.
 ** https://github.com/castle-engine/castle-engine/tree/master/examples/animations/expose_transformations_to_animate_children[animations/expose_transformations_to_animate_children] - attach objects to animated bones, e.g. attach a weapon (switch at runtime between a sword, axe, nothing...) to character's hand.
 ** https://github.com/castle-engine/castle-engine/tree/master/examples/advanced_editor[advanced_editor] - advanced usage of UI designs (`xxx.castle-user-interface`), transformation designs (`xxx.castle-transform`, like prefabs in Unity), and creating and registering custom editor components. See news: https://castle-engine.io/wp/2020/12/20/new-tcastletransformdesign-component-like-prefab-for-tcastletransform-example-advanced_editor-showing-advanced-usage-of-designs-and-custom-components/ .
 ** https://github.com/castle-engine/castle-engine/tree/master/examples/3d_rendering_processing/collisions[collisions] - demo of using our collision routines.
* Android improvements:
 ** --target=android to build both 32-bit and 64-bit binaries.
 ** New https://github.com/castle-engine/castle-engine/wiki/Android-Services[Android services]:
  *** facebook,
  *** apps_flyer,
  *** freetype,
  *** download_urls
  *** read_external_storage
  *** write_external_storage
 ** Many upgrades to build infrastructure (new Gradle version etc.)
 ** AdMob upgraded, and supports TAdWatchStatus that reports _why_ user did not watch the ad.
* iOS improvements:
 ** https://github.com/castle-engine/castle-engine/blob/master/tools/build-tool/data/ios/services/vibrate/README.md[Vibrations].
 ** GPU compressed textures support for square textures (Apple makes it harder to support non-square textures).
 ** Build tool has command-line options to create IPA file or even upload the build to TestFlight, see https://github.com/castle-engine/castle-engine/wiki/iOS[iOS building page].
 ** https://castle-engine.io/manual_text.php[FreeType is supported] so you can freely load fonts at runtime.
* Other https://github.com/castle-engine/castle-engine/wiki/Build-Tool[build tool] improvements:
 ** https://castle-engine.io/creating_data_auto_generated_textures.php[Packaging of textures specific to given platform]
 ** Filtering of messages (better output, that avoids some unnecessary warnings from specializing generics containers, but at the same time leaves these warnings enabled for your code)
* Physics improvements:
 ** Collision detection (TRigidBody.GetCollidingTransforms, OnCollisionEnter, OnCollisionExit).
 ** https://castle-engine.io/wp/2019/11/02/triggers-detecting-collisions-and-physics-settings/[Triggers and physics settings]
 ** And more, see https://castle-engine.io/wp/2019/06/15/physics-collision-detection-and-new-properties/
* Sound improvements:
 ** Split into multiple backends, and FMOD backend added, see https://github.com/castle-engine/castle-engine/wiki/FMOD .
 ** More features for sounds XML files, like aliases and groups. See https://castle-engine.io/wp/2019/04/29/new-sound-features-alternative-backends-new-demo-aliases/
 ** LoopingChannel, to easily play multiple sound tracks, ambience tracks etc.
 ** https://castle-engine.io/wp/2019/08/18/streaming-sound-tracks-fmod-linking-improved/[Sound streaming].
 ** New way to play sounds by `TCastleSound` and `TCastleSoundSource` (TODO: in progress to make it clickable in CGE editor)
* Last but not least, stuff "around" CGE:
 ** Docker image with docs: https://castle-engine.io/wp/2019/02/16/using-castle-game-engine-with-docker/
 ** New forum https://forum.castle-engine.io/
 ** License simplified. The engine is "LGPL with static linking exception" (i.e. you can use it in commercial applications) out-of-the-box. See https://castle-engine.io/wp/2018/05/30/nurbs-simplified-license-just-lgpl-out-of-the-box/ and https://github.com/castle-engine/castle-engine/blob/master/COPYING.md for details.
 ** API searching, switching between stable/unstable API docs.
 ** https://castle-engine.io/wp/2020/09/27/new-patreon-rewards-and-goals-since-october-including-plans-for-training-videos-conferencegamejam-occulus-port/[New Patreon rewards and goals] including conferences, Occulus port and more :)

== Advise for upgrading: Upgrade your pipeline from X3D to glTF

While X3D is still our _scene graph format_ (which means that everything you render is composed from X3D nodes in memory, which practically means: Pascal classes `TXxxNode`), our main _file format_ is now glTF, not X3D (which means that we advise to export from Blender to glTF, not to X3D).

The reason for that is practical. glTF is just better now, as a file format:

* Although X3D offers a lot of features, but the existing Blender \-> X3D exporter is extremely poor. It doesn't support many features (e.g. it cannot export animations, or even textures in the latest version).
* Moreover, the existing Blender \-> X3D exporter doesn't support features which are CGE extensions or are only in X3D 4.0, like PBR or normalmaps. We had an extended CGE exporter (to X3D) for older Blender, but it was too much burden to maintain. We also had castle-anim-frames exporter, but castle-anim-frames is a poor solution compared to proper glTF skinned animation.
* Existing Blender \-> glTF is actively maintained (by Khronos together with Blender), and supports all the features we like. In particular PBR, all possible textures and normalmaps, unlit materials, animations by transformations, animations by skinning, by morphing, metadata (from Blender custom properties).
* glTF ecosystem is more active. By this I mean that great quality glTF models can be found e.g. on Sketchfab.
* glTF is much smarter about "binary data vs text data", which results in it being both simpler and more efficient. glTF uses a binary stream for data that should be uploaded to GPU (in particular everything per-vertex), and it uses JSON stream for other things. This makes glTF files much faster to load. In contrast, X3D text files encode 100% things in text (and thus are often huge and slow to load), unless one uses X3D binary encoding (which is not implemented in CGE, and probably will never be -- as it is still poor compared to glTF, as it only speeds up parsing but data still needs to be repacked for GPU).

So it seems reasonable to "just switch to glTF". I can now rely on Khronos to work on Blender \-> glTF exporter.

We advise you to use glTF for all your future games, instead of X3D, now.

You can, although you don't have to, switch your existing games to use glTF too. Of course we continue to support X3D model format in 100%, so you don't have to. Things to watch out for:

* In case of Blender, both the X3D exporter and glTF exporters convert (by default) "up" from +Z to +Y. However, they do it in a little different way. In effect, if you design a creature following Blender "front" convention, then it will look toward -Z direction after being exported to X3D, but in +Z direction after being exported to glTF. To be precise, X3D output is rotated 180 degrees around (0,1,0) compared to X3D output.
 ** For games using X3D exporter for creatures, call "TCastleTransform.DefaultOrientation := otUpYDirectionMinusZ". This was the default in CGE 6.4, but in CGE 7.0 the default is matching glTF convention, which is "TCastleTransform.DefaultOrientation := otUpYDirectionZ".
 ** If you switch your level models from X3D to glTF, remember to adjust any position you manually define (e.g. in code). Adjust it by rotating 180 degrees around (0,1,0). (For positions, you can just negate X and Z coordinates to achieve this.) E.g. camera or lights positions, if you ever define them in code.
* The glTF exporter will create materials using PBR (physically-based rendering). If you prefer to use Phong lighting model (because it is faster, or because it just looks better in your specific case) then you can define GltfForcePhongMaterials (global variable in CastleLoadGltf unit) before doing any loading. If you don't \-> remember that materials will just look different, and you need to manually adjust them (automatic conversion is not possible, as there are just different equations underneath).
