# States
include::common.adoc[]

<?php
echo castle_thumbs(array(
  array('filename' => 'zombie_fighter_1.png', 'titlealt' => 'Multiple viewports and basic game UI'),
  array('filename' => 'zombie_fighter_2.png', 'titlealt' => 'UI dialog, in a state over the game UI'),
));
?>

## Introduction

We advise to organize your game into a number of <i>"states"</i>. In the typical approach, the game is always within some state and each state also has a matching user-interface design.

This chapter assumes you have tested basic working with the state, following link:manual_state_events.php[Designing user interface and handling events (press, update) within the state] chapter.

## Example

Almost every example in CGE is organized in states. Some bigger examples:

- https://github.com/castle-engine/castle-engine/tree/master/examples/platformer[platformer] defines states for main menu, options (with volume configuration), pause, credits, game over and of course the actual game.

- https://github.com/castle-engine/castle-engine/tree/master/examples/user_interface/zombie_fighter[zombie_fighter] defines main menu, loading state, ask dialog, and the actual game in <code>TStatePlay</code>.

## Usage

<p>In the typical usecase, you create many descendants of the class
<?php api_link('TIUState', 'CastleUIState.TUIState.html'); ?>. Each descendant represents a different state,
like <code>TStateMainMenu</code>,
<code>TStatePlay</code>, <code>TStatePause</code> and so on. Usually you create a
single instance for each of these classes, at the beginning of your
game in <?php api_link('Application.OnInitialize', 'CastleWindow.TCastleApplication.html#OnInitialize'); ?> handler.

<p>Each state loads the user-interface appropriate for the
given state. The advised way to do this is to set cgeref:TUIState.DesignUrl[] in the overridden state constructor,
like

[source,pascal]
----
constructor TStateMain.Create(AOwner: TComponent);
begin
  inherited;
  DesignUrl := 'castle-data:/gamestatemain.castle-user-interface';
end;
----

The <?php api_link('TIUState', 'CastleUIState.TUIState.html'); ?>
 is a special <?php api_link('TCastleUserInterface', 'CastleUIControls.TCastleUserInterface.html'); ?>
 descendant. As such, you can add there more UI children in a number of ways, and you can actually add/remove them
 at any moment. For example

<ul>
  <li><p>Or you can add children in every <?php api_link('Start', 'CastleUIState.TUIState.html#Start'); ?>
    call, overriding it. In this case, you
    should remove the controls in the <?php api_link('Stop', 'CastleUIState.TUIState.html#Stop'); ?> method.
    Or you can set the controls' owner
    to a special <?php api_link('FreeAtStop', 'CastleUIState.TUIState.html#FreeAtStop'); ?> component,
    to make them freed and removed automatically at the next
    <?php api_link('Stop', 'CastleUIState.TUIState.html#Stop'); ?> call.</p></li>

  <li><p>For advanced uses, if you will use the state stack, you can
    also add / remove children in the
    <?php api_link('Resume', 'CastleUIState.TUIState.html#Resume'); ?> and
    <?php api_link('Pause', 'CastleUIState.TUIState.html#Pause'); ?> calls.</p></li>
</ul>

<p>During the game you use <?php api_link('TIUState', 'CastleUIState.TUIState.html'); ?>
 class methods and properties to change the
current state. Most importantly, you can simply change to a new state
by setting "<?php api_link('TUIState.Current', 'CastleUIState.TUIState.html#Current'); ?> := NewState;". This will call
<?php api_link('Stop', 'CastleUIState.TUIState.html#Stop'); ?> on the
old state, and <?php api_link('Start', 'CastleUIState.TUIState.html#Start'); ?>
 on the new state (these are methods that you can override to do something useful).

<p>For advanced uses, you can also have a <i>"state stack"</i>. This is
perfectly useful when one user-interface is displayed on top of
another, for example when the <code>TStatePause</code> shows a dimmed state of the
game underneath. Be sure to actually pause the game underneath; you
can make a "dimmed" look by adding a fullscreen
<?php api_link('TCastleRectangleControl', 'CastleControls.TCastleRectangleControl.html'); ?>
 with a transparent color (that has alpha between 0 and 1,
like 0.5). If you don't want the underlying state to also receive the
inputs, be sure to set <?php api_link('InterceptInput', 'CastleUIState.TUIState.html#InterceptInput'); ?> on the top state
(<code>TStatePause</code> in this example).

<p>To actually change the state using the "stack" mechanism, use the
<?php api_link('TUIState.Push', 'CastleUIState.TUIState.html#Push'); ?> and
<?php api_link('TUIState.Pop', 'CastleUIState.TUIState.html#Pop'); ?> methods.
