# Units Map
include::common.adoc[]

== Introduction

_Castle Game Engine_ includes a lot of units. They are divided into groups, which correspond to the subdirectories in the engine `src` subdirectory: `transform`, `audio` and so on. The groups are shortly described below.

## Dependencies

One of the ways how we keep the engine maintainable is to limit the dependencies between unit groups. For example, the transformation and UI stuff depends on images, but the units in the `images` group cannot depend on units in the `transform` or `ui` groups. A simple dependency tree allows to easily debug some hard problems (when you want to strip the used units, to get to the "bottom of the problem").

The allowed dependencies are listed below. In short, the list of subdirectories goes from "lower level" to "higher level" in the sections below.

*These dependencies are automatically checked* (by https://github.com/castle-engine/castle-engine/tree/master/tools/internal/check_units_dependencies[tools/internal/check_units_dependencies], executed by Jenkins after every push).

NOTE: Temporarily, some units are allowed exception to break from this rule. Right now 3 units have such exception, i.e. they actually break dependencies outlined below. See https://github.com/castle-engine/castle-engine/blob/master/tools/internal/check_units_dependencies/check_one_unit_dependencies.lpr#L91[AllowedExceptions list in check_units_dependencies]. This is a TODO -- we *will* fix those. It's also a practical decision -- while we want to watch over these dependencies, in practice breakage (in some cases) has no bad consequences.

== Unit groups

=== castle_base package

==== base

Basic utilities and classes. Stuff for dealing with vectors, colors, strings, Unicode, logging, rectangles...

_Depends on_: nothing else.

==== files

Files, URLs, XML utilities, downloading files from the network. See link:manual_network.php[manual about network and downloading].

_Depends on_: everything above (that is, units in "base" group).

==== audio

Sound files loading, sound playback (including 3D sound), processing of sound files. See link:manual_sound.php[manual about sound].

_Depends on_: everything above (that is, units in "base" and "files" groups).

==== images

Image loading and saving: cgeref:TCastleImage[], cgeref:TGPUCompressedImage[] (with ancestor cgeref:TEncodedImage[]).

_Depends on_: everything above except audio.

==== base_rendering

OpenGL(ES) basic units. Headers, loading images/textures to OpenGL(ES), rendering basic 2D primitives (cgeref:TDrawableImage[], cgeref:DrawPrimitive2D[]).

_Depends on_: everything above except audio.

==== fonts

Loading font data from files using FreeType, rendering text (cgeref:TCastleFont[]), converting font data to be embeddable as Pascal units.

_Depends on_: everything above except audio.

==== ui

2D user interface of the engine: cgeref:TCastleContainer[], cgeref:TCastleUserInterface[], lots of cgeref:TCastleUserInterface[] descendants like buttons, rectangles, labels... Also keyboard, mouse and other input handling.

_Depends on_: everything above.

==== services

Integration with environment (operating system). Opening a document, making a mobile payment, sending analytics data...

NOTE: The unit cgeref:CastleMessaging[], important for Android services, is inside the `base` group, not here (since nearly everything else can use it, e.g. sound engine needs to use it).

_Depends on_: everything above.

==== transform

Basic transformation stuff, in particular cgeref:TCastleTransform[], cgeref:TCastleCamera[]. Also quaternions, axis-aligned bounding box types.

_Depends on_: everything above.

==== castlescript

Parsing and executing expressions and programs in the  link:castle_script.php[CastleScript language].

_Depends on_: everything above.

==== scene

The core of our engine rendering and processing for typical games:

* cgeref:TCastleScene[]: loading many 2D and 3D formats, rendering, writing and processing (animating, collisions..).
* cgeref:TCastleViewport[] to display 2D and 3D scenes.

_Depends on_: everything above.

Subdirectories:

scene/x3d:: 2 big units that define all X3D base concepts: cgeref:X3DFields[], cgeref:X3DNodes[].

scene/load:: cgeref:X3DLoad[] and friends to load particular scene formats. Some formats have their own subdirectory, like `scene/load/spine/`.

=== castle_window package

==== window

cgeref:TCastleWindow[], window with an OpenGL context.

_Depends on_: `castlescript`.

NOTE: In the past it depended on more (even `scene`) but there should not be a need for this now. Window allows to add cgeref:TCastleUserInterface[] and cgeref:TCastleView[] inside, it should not deal with viewports/scenes specifics directly.

=== castle_components package

==== lcl

cgeref:TCastleControl[], a Lazarus component to render with our engine.

_Depends on_: `ui`. (not `castlescript` for now, doesn't need it.)

This is an alternative to TCastleWindow, so it has the same dependencies. Units between `window` and `components` group cannot use each other.

NOTE: In the past it depended on more (even `scene`) but there should not be a need for this now. Window allows to add cgeref:TCastleUserInterface[] and cgeref:TCastleView[] inside, it should not deal with viewports/scenes specifics directly.
