# Tutorial: Designing a 3D world
include::common.adoc[]

## Introduction

In this chapter we show how you can design 3D world using _Castle Game Engine_ editor. We assume you have already read the link:viewport_and_scenes[overview of the viewport and scenes].

## Complete tutorial code

The complete result of this tutorial is in the _Castle Game Engine_. Just open the project https://github.com/castle-engine/castle-engine/tree/master/examples/viewport_and_scenes/viewport_3d_tutorial[examples/viewport_and_scenes/viewport_3d_tutorial] in the editor. If at any point you get lost, just look there.

## Create empty project, add a viewport

. Run _Castle Game Engine editor_, create a new project using the _Empty_ template.
+
cgeimg::block[viewport_3d_editor_project.png|Create new project]

. Open the `data/gamestatemain.castle-user-interface` design using the _Files_ panel at the bottom of the editor. Enter `data` subdirectory and double-click on `gamestatemain.castle-user-interface`.
+
cgeimg::block[viewport_3d_design.png|Open the design]

. Add a cgeref:TCastleViewport[]. Resize it as you like, or just set cgeref:TCastleUserInterface.FullSize[FullSize] to `true` to have it will the entire window.
+
You also want to move it in the hierarchy, such that it is _underneath_ the `LabelFps` component. This way you will see FPS counter over the viewport.
+
cgeimg::block[viewport_3d_add_viewport.png|Add viewport]

## Add a scene showing the 3D car, adjust camera, lights and navigation

. Add a cgeref:TCastleScene[] to cgeref:TCastleViewport.Items[]. It is easiest to do by right-clicking on the `Items` in the editor hierarchy (panel on the left side), and choosing _Add Transform -> Scene (TCastleScene)_ from the menu that appears.
+
cgeimg::block[viewport_3d_add_scene.png|Add scene,viewport_3d_scene_added.png|After adding a scene]

. Now you need some 3D assets to actually play with.
+
We advise at this point that you take the sample 3D asset of a car and road we have in our examples. Open in your file manager the https://github.com/castle-engine/castle-engine/tree/master/examples/viewport_and_scenes/cars_demo/data[examples/viewport_and_scenes/cars_demo/data] subdirectory of your _Castle Game Engine_ sources. Select there the files:
+
--
** `car.bin`
** `car.gltf`
** `road.bin`
** `road.gltf`
** Whole `textures/` subdirectory.
** Optionally, select also `car.blend` and `road.blend`.  _Castle Game Engine_ doesn't read `.blend` files, but you can modify them in link:creating_data_blender.php[Blender] and export to glTF, to play with what you can do in 3D.
--
+
cgeimg::block[viewport_3d_select_data.png|Files to copy]
+
Copy these files into your new project, into the `data` subdirectory. It is easiest to open it by right-clicking on `data` in CGE editor, and choosing _Open In File Manager_ from the context menu that appears.
+
If you already have some 3D assets (see link:creating_data_model_formats.php[3D assets formats we support]) you can of course use at this point already.

. Try the _preview_ feature of the editor at this point. Just select (click once) the `car.gltf` file. If you copied everything correctly (including `car.bin` and `textures/`), it will display the 3D car model in a preview window that appears in the bottom-right corner.
+
cgeimg::block[viewport_3d_preview.png|Preview]

. Set your `Scene1.URL` property to the `car.gltf` model in your data. To do this, select `Scene1` in the _hierarchy_ (left panel of the editor), then look for `URL` in the _object inspector_ (right panel of the editor), and click on the small button with 3 dots `...` in the edit field next to the `URL`. This will open a normal dialog window, where you should select the `car.gltf` in your project's data.
+
Once you accepted this, note that the `Scene1.URL` changed the `castle-data:/car.gltf`. In general, this is an URL of the file. It uses a special `castle-data` protocol to indicate that the file is in the project's special link:manual_data_directory.php[data directory].
+
Note that instead of clicking on the button with 3 dots, you could have also pasted the URL `castle-data:/car.gltf` in the edit field. It's a simple text field, you can edit it like any other text field if you need to, and it will reload the loaded model. You can set the `URL` to empty always to unload the model.
+
cgeimg::block[viewport_3d_added_car.png|Added car]

. While the car loaded, your camera likely doesn't show anything pretty. That is because the default camera view doesn't look at the car in a nice way.
+
The default camera stands at the `0 0 0` position, and looks in the -Z direction. You can check it out looking at `Viewport1.Camera.InitialPosition` and `Viewport1.Camera.InitialDirection` values in the object inspector (you will probably need to _expand_ the `Viewport1.Camera` properties). And the car is a model positioned over the `0 0 0` point. So the camera looks underneath the car.
+
cgeimg::block[viewport_3d_camera_bad.png|Initial camera position and direction]
+
Fix it now using the _Camera Current := View All_ command from the _"hamburger"_ menu of the viewport on top. This menu is available whenever you have selected a cgeref:TCastleViewport[] or any transformation within the viewport.
+
cgeimg::block[viewport_3d_viewport_menu.png|Menu with camera commands]
+
Next use the menu _Camera Initial (stored in the design file) := Current_ command, so that the game would also start with the new view. You can look at `Viewport1.Camera.InitialPosition` and `Viewport1.Camera.InitialDirection` values again, to see that at least the position have changed.
+
cgeimg::block[viewport_3d_camera_better.png|Better camera position]

. That is a better view (at least the whole car is visible) but the car is still completely black. That is because we don't have any lights in the viewport yet. Solve it by turning on the simple _"headlight"_ (light that shines from the camera). To do this, set `Viewport1.Items.UseHeadlight` value to `hlOn`.
+
In larger applications, you will probably add more lights, designed at specific positions in the 3D world. To do this, right now you have to design the lights in a 3D authoring application (like link:creating_data_blender.php[Blender]) and export them to glTF. Set the scene with lights as `Items.MainScene` to make the lights shine on everything. In a very near future (beginning of 2022), we want to add lights editing directly to the editor, so it will be easier. For now, for this demo, the _"headlight"_ may be enough.
+
cgeimg::block[viewport_3d_headlight.png|After turning on the headlight]

. While the car is now visible, the default camera view (set by the _Camera Current := View All_ command) isn't very interesting. to improve it, you shoud use some _navigation_ within the editor, and set more interesting camera. To do this, use _Change Navigation -> Examine (TCastleExamineNavigation)_ from the viewport hamburger menu. It will add an instance of `TCastleExamineNavigation` to your design, and automatically make it active for this viewport.
+
cgeimg::block[viewport_3d_change_navigation.png|Change Navigation]
+
Now switch to the editor mode _"Use components as a normal user"_ to use the examine navigation, just as normal user of your application would be able to use `TCastleExamineNavigation`.
+
cgeimg::block[viewport_3d_change_mode.png|Change Mode]
+
--
Now you can:

** Drag with left mouse button to rotate.
** Use mouse scroll to zoom in/out. Or drag with right mouse button. Or drag with left mouse button with the `Ctrl` key pressed.
** Drag with the middle mouse button to move. Or drag with left mouse button with the `Shift` key pressed.
--
+
Use these features to set some nice view that shows the entire car.
+
cgeimg::block[viewport_3d_nice_view.png|Nice view]
+
Once you're done use the _Camera Initial (stored in the design file) := Current_ command again, to store the new view (camera position, direction, up) to be used as starting camera view during the game.

. Decide if (and how) should the user be able to navigate during the game.
** For now, we recommend you leave the `TCastleExamineNavigation` instance (called `ExamineNavigation1` in your hierarchy) existing in your design, then the user will be able to change camera just like you did.
** But you can change the navigation to something else, using the _Change Navigation -> ..._ menu commands.
** In particular, you can set the navigation to _None_ to disallow user from making any changes to the camera. This is reasonable, if you want to have a constant camera view, or implement the navigation yourself (for example moving/rotating the camera by your own code in `TStatePlay.Update`).

## Run the game

Run the game at this point! Just press F9 in the editor.

cgeimg::block[viewport_3d_run.png|Game running]

## Play animation

There is a simple animation called `wheels_turning` defined in the `car.gltf` model. Let's configure the scene to automatically play it.

To do this, just edit the cgeref:TCastleSceneCore.AutoAnimation[AutoAnimation] property. You can choose one of the existing animations using the combo box there. Leave the cgeref:TCastleSceneCore.AutoAnimationLoop[AutoAnimationLoop] property at default value of `true` to make the animation looping.

cgeimg::block[viewport_3d_animation.png|Playing animation]

NOTE: During the game, you can switch the animation to a different one. You can do this by setting the cgeref:TCastleSceneCore.AutoAnimation[AutoAnimation] and cgeref:TCastleSceneCore.AutoAnimationLoop[AutoAnimationLoop] from code, but usually it is more comfortable to use the cgeref:TCastleSceneCore.PlayAnimation[PlayAnimation] method. Chapter link:viewport_and_scenes_from_code[Writing code to modify scenes and transformations] shows how to do this.

## Add a road and more cars

Your viewport may contain many scenes. This is how you can design 3D game levels using the _Castle Game Engine editor_ -- just add various cgeref:TCastleTransform[] (including cgeref:TCastleScene[]) instances to the viewport, and arrange them (move, rotate, scale) as needed.

. Add another scene to the viewport (right-click on the `Items` property of the viewport).
+
Call it `SceneRoad` (edit the `Name` property in object inspector, or press F2 in the hierarchy to edit the name).
+
Set its `URL` to point to the `castle-data:/road.gltf` model.
+
cgeimg::block[
  viewport_3d_add_road.png|Add another scene,
  viewport_3d_road_name.png|Edit scene name,
  viewport_3d_road_url.png|Set road URL
]

. Edit the car scene name too, to make it more obvious in the hierarchy. Right now it is called `Scene1`, we recommend to edit it to `SceneCar` now.

. Add more cars. While you could add new cgeref:TCastleScene[] instances, by repeating the process above, it is easier to use _"Duplicate"_ command available when you righ-click on the `SceneCar`. (Key shortcut to do this is _Ctrl+Shift+D_.)
+
New car scenes, named like `SceneCar1`, `SceneCar2`..., will appear at the same position as the original car. Use the _"Move/Select Transform_" tool to show a _"gizmo"_, to move each car to a unique position. Click and drag on one of the arrows to move the car.
+
You can observe that moving the car using gizmo also updates it's `Translation` property in the _Layout_ tab. You can also move the car by just editing the numbers there, to manually input X, Y, Z movement values.
+
Remember that you can adjust the camera to see more 3D space, to keep all the cars in view. Use the _Camera Initial (stored in the design file) := Current_ command to set the best initial camera.
+
cgeimg::block[
  viewport_3d_duplicate.png|Duplicate scenes,
  viewport_3d_car_move.png|Move scenes,
  viewport_3d_translation_vector.png|View and edit the Translation values as numbers
]

## Run the game again

Run the game again at this point, to test that you can view the road and animated cars. Just press F9 in the editor.

cgeimg::block[viewport_3d_game_2.png|Game running with many cars and road]

## Walk around the level

Now that we have constructed a simple 3D world, composed of multiple scenes (cars and road), it would be nice to walk around in this world using typical FPS (first-person shooter) controls.

. We recommend first to duplicate the `SceneRoad` a few times, to have a large floor area to walk on.
+
cgeimg::block[viewport_3d_floor.png|Multiple road scenes to create a large floor]

. Switch navigation mode to _Walk_. It will remove the `ExamineNavigation1` instance from your design, and add `WalkNavigation1`.
+
cgeimg::block[viewport_3d_navigation_mode_walk.png|Switch to walk navigation]

. Change the cgeref:TCastleWalkNavigation.MoveSpeed[] property of your `WalkNavigation1` to move faster (both at design-time, and for user during the game). We recommend to set it to 10 now, which means you will move with speed of 10 units (meters) per second. This is not realistic (people are not that fast), but it allows for comfortable testing. Players in games often move unrealistically fast.
+
cgeimg::block[viewport_3d_move_speed.png|Adjust walk navigation MoveSpeed]

. Switch to _"Use components as a normal user."_ mode using the toolbar, if you're not in this mode already.

. Temporarily turn off cgeref:TCastleWalkNavigation.Gravity[] property. While gravity doesn't work anyway at design-time (so your camera will not "fall down" at design time), but turning off `Gravity` is still useful for now to make the _C_ (move down) and _Space_ (move up) keys work more naturally.

. Move around the level now, using the "walk" navigation keys.
+
--
- Use _A W S D_ keys for typical 3D game movement (forward, backward, strafe).
- Use _C_ key to move down.
- Use _Space_ key to move up.
- Drag with left mouse button to move and rotate.
- Use mouse scroll to raise your head / bow down.
--
+
Using these keys, place the camera at some nice position above the floor, such that it looks at cars.
+
cgeimg::block[viewport_3d_walk_camera.png|Initial camera for walking]

. Change the cgeref:TCastleWalkNavigation.Gravity[] back to `true`, to make gravity work in game.

. Use _Camera Initial (stored in the design file) := Current_ again, to store the current camera as a starting view view for the game.

. If your camera is a little tilted to the side, we recommend to reset the initial camera `InitialUp` to be a straight (0,1,0) vector. This makes movement for user most natural. Select the `Viewport1` in the hierarchy, then expand the `Camera` in the object inspector on the right, and paste `0 1 0` as the value for `InitialUp`.
+
Use _Camera Current := Initial (stored in the design file)_ to set the `InitialUp` as the current camera up, to immediately preview the newly set camera.
+
cgeimg::block[viewport_3d_camera_up_reset.png|Reset camera up]

. Increase the cgeref:TCastleWalkNavigation.PreferredHeight[] of the `WalkNavigation1` component. The default value is 1.6, which means that player's height is 1.6 meters when standing -- this corresponds to a normal (not very tall) human. For games, reasonable (but still somewhat realistic) values could be considered between 1.6 and 2.0 (players in games are often tall).
+
For this demo, for now, we recommend you set this value to a big number: 4.0. This is not realistic at all (humans are rarely 4 meters tall :) ), but it will allow to test walking quickly, and will allow you to "walk over" cars. It also matches the unrealistic
+
cgeimg::block[viewport_3d_preferred_height.png|Adjust PreferredHeight]

## Run the game - final test!

Run the game again with F9. Walk, using the same keys, or mouse dragging, as before. Use mouse scroll to raise / bow your head.

As gravity is active now, the _C_ key does _crouch_ and _Space_ key does _jump_.

Walk over the cars and jump over them to test collisions and gravity.

cgeimg::block[viewport_3d_game_running_walk.png|Game running with walking]

## Further things

### Lighting

Because of how the headlight works (it is a simple directional light by default), and the fact that we don't have any additional lights on the level -- the road is completely dark when looking straight ahead. You need to bow your head (use mouse scroll) to have a bit brighter road.

This should be fixed by adding additional lights to the level.

*Advised solution:* Add light(s) to the scene using the _Castle Game Engine_ editor. Simply add them to the viewport (right-click on the `Items` property of the viewport). Then move/rotate them as needed. The following light sources are available:

- cgeref:TCastlePointLight[] - omnidirectional light that shines with a certain cgeref:TCastlePointLight.Color[Color], cgeref:TCastlePointLight.Intensity[Intensity] and cgeref:TCastlePointLight.Radius[Radius]. The rotation of this light doesn't matter, only the position influences the actual effect.

- cgeref:TCastleDirectionalLight[] - light that shines along a certain direction, with certain cgeref:TCastleDirectionalLight.Color[Color] and cgeref:TCastleDirectionalLight.Intensity[Intensity]. It approximates a light source that is very very far away, like a real-world sun. The position of this light source doesn't matter, only the rotation influences the actual effect.

- cgeref:TCastleSpotLight[] - light that shines from a given position, in a given direction, within a cone. The cone angle is configurable (by cgeref:TCastleSpotLight.CutOffAngle[CutOffAngle] and cgeref:TCastleSpotLight.BeamWidth[BeamWidth]), as well as cgeref:TCastleSpotLight.Color[Color], cgeref:TCastleSpotLight.Intensity[Intensity] and cgeref:TCastleSpotLight.Radius[Radius].

*Alternative solution:* You can also add lights in Blender to the road asset.

. Copy `road.blend` to `road_with_lights.blend`.
. Add lights in Blender to `road_with_lights.blend`.
. Export it to `road_with_lights.gltf` (be sure to select to include _"Lights"_ at glTF export dialog).
. Change one road piece, like the initial `SceneRoad`, to load from `road_with_lights.gltf` (instead of `road.gltf`).
. Set `SceneRoad` as `Items.MainScene` to make the lights shine on all the other scenes -- cars and other road pieces.

cgeimg::block[
  viewport_3d_lights_blender.png|Adding lights in Blender,
  viewport_3d_export_lights.png|Exporting lights from Blender,
  viewport_3d_main_scene.png|Setting new road as MainScene,
  viewport_3d_brighter.png|Brighter world with more lights
]

### "Mouse look" navigation

The walk navigation is easiest if you use _mouse look_. It will allow to move the mouse to rotate around.

#### Turn on by default

You can activate this by just setting `WalkNavigation1.MouseLook` property to `true`. Setting this property doesn't change the navigation in the editor, but once you run the game the _mouse look_ will work. The game will grab your mouse, and you will rotate by moving the mouse.

Note that, as we grabbed the mouse but didn't provide any way to "escape" from it, you cannot easily close the game window by clicking on the usual "close" button on the window frame. Just press Alt+F4 on most systems to close it.

#### Allow to turn on/off using code

Instead of having the _mouse look_ just active by default, we can make it active e.g. only once you click the _right mouse button_. Clicking the button again could deactivate it.

Such behavior has to be implemented using the code. Chapter link:viewport_and_scenes_from_code[Writing code to modify scenes and transformations] describes how to edit the game code. We don't want to get ahead of ourselves... But actually it is quite easy. Just edit the `code/gamestatemain.pas` file, and

. Add `CastleCameras` unit to the `uses` clause in the `interface`.
. Declare `WalkNavigation1: TCastleWalkNavigation;` inside the `private` section of the `TStateMain`, under the comment _{ Components designed using CGE editor, loaded from gamestatemain.castle-user-interface. }_.
. In `TStateMain.Start` implementation, add this code:
+
[source,pascal]
----
WalkNavigation1 := DesignedComponent('WalkNavigation1') as TCastleWalkNavigation;
----
. In `TStateMain.Press` implementation, add this code:
+
[source,pascal]
----
if Event.IsMouseButton(buttonRight) then
  WalkNavigation1.MouseLook := not WalkNavigation1.MouseLook;
----

### More precise collisions

The collisions work correctly in this simple demo, as both the road and cars have simple shapes that can be approximated using boxes. In general, your levels will probably have more complicated shapes. To make any shape work nicely with default navigation collisions, set the `Spatial` property of your scenes to include the `ssDynamicCollisions` flag. We recommend to include also the `ssRendering` flag to optimize the display of scenes with multiple shapes.

Do this for all your scenes, both cars and roads. Note that you can select multiple scenes in the hierarchy with _Ctrl_ and then edit the `Spatial` property of all selected scenes at one.

cgeimg::block[viewport_3d_spatial_all_scenes.png|Edit Spatial of all scenes]

### Multiple instances of the same scene (using TCastleTransformReference)

It is possible to optimize the usage of resources, when you want to instantiate the same resource multiple times, and each instance has the same state (which means that it is static, or plays the same animation).

. Remove the car copies you made with _"Duplicate"_ command earlier. You'll add copies in a different way. Leave only one car, `SceneCar`.
. To make things more intuitive in the following points, remove any translation you may had on `SceneCar`. You can do this using _"Reset Transform"_ in the _"Layout"_ tab of the object inspector. You could also just type `0 0 0` into the `SceneCar.Translation` value.
+
NOTE: If you need to translate even this one car, then add an intermediate transformation like `TransformCar`. Add this to `Viewport.Items`, and drag `SceneCar` to be a child of `TransformCar`. Then you can change translation of `TransformCar` to move your 1st car.
+
NOTE: You can also just disregard this advise, and leave non-zero translation on `SceneCar`. It works, but it means that each reference also has a shift -- you'll see what we mean by this next. It may be non-intuitive at the beginning.
. Add a cgeref:TCastleTransformReference[] to the `Viewport.Items`.
.. Set it's `Reference` property to point to the `SceneCar`.
.. And move it wherever you like.
.. Change it's name to be something better than default `TransformReference1`. We propose to change it to `SceneCarReference1`.
. Duplicate the `SceneCarReference1` as many times as you want to, and translate each instance differently.

*Done.* Now you can have lots of cars -- yet they all share the same data, by referencing (in memory) the same `SceneCar` instances. This is great to conserve resources and speed when you need *a lot* of instances of something. E.g. this would be great for trees on a big outdoors level.
