# Designing a 2D world
include::common.adoc[]

cgeimg::float[platformer.png|Platformer game]

## Introduction

In this chapter we show how you can design 2D world using _Castle Game Engine_ editor. We assume you have already read the link:viewport_and_scenes[overview of the viewport and scenes].

[WARNING]
====
This page is a work in progress.

We plan to write here a detailed tutorial, similar to link:viewport_3d[Tutorial: Designing a 3D world], but designed specifically for 2D games (using static images for a background, using sprite sheets for hero and some enemies).

But it is not ready yet.

For now, we advise to follow link:viewport_3d[Tutorial: Designing a 3D world], and then read this page about important things that are different for 2D games.
====

## Examples

Consult the engine examples, like https://github.com/castle-engine/castle-engine/tree/master/examples/platformer[examples/platformer], for a fully-working game following this approach.

## Create a viewport for 2D

Create a viewport in the editor by right-clicking in the hierarchy and using _"Add User Interface -> Viewport (2D)"_ menu item.

This creates a viewport with 2D navigation, 2D orthographic camera, and adds a default white plane in the middle. By default in 2D:

- X axis goes to the right,

- Y goes up,

- Z axis is "depth". Camera looks in the -Z direction. Larger Z means that object is closer to the camera (_in front_ of other objects), smaller Z means that it is further from the camera (_behind_ other objects). Is it OK to use negative Z values.
+
NOTE: For 2D objects will blending, you may (for now) need to sort the hierarchy after setting their Z, using _"Viewport -> Sort Items For Correct 2D Blending"_.

## Navigation in 2D

In a viewport created using the _"Add User Interface -> Viewport (2D)"_ menu item we use, by default, a special _2D_ navigation method.

- Drag with right mouse button to pan the view,

- Use mouse scroll wheel to zoom in / out.

This makes it easy to move a 2D scene, without accidentally making a rotation that would reveal it is 3D.

NOTE: If you want to allow user to easily pan/zoom the view, add the cgeref:TCastle2DNavigation[] component as a child of the cgeref:TCastleViewport[].

NOTE: You *can* still use a different navigation, like 3D _Fly_ navigation. Use the _"Viewport"_ menu item commands to toggle between different navigation methods.

## Orthographic projection

A viewport created using the _"Add User Interface -> Viewport (2D)"_ menu item will use an _orthographic_ projection by default.

In such projection, the distance to the object doesn't change its perceived size. Constrast this with the _perspective_ projection, default in 3D, in which the objects further away are perceived as smaller.

You can always change the camera projection manually using the cgeref:TCastleCamera.ProjectionType[] property. This sets the projection used at runtime (when you run the game). You can also change the projection used at design-time (in the editor) using the _"Viewport -> Toggle Perspective / Orthogonal"_ menu item.

## Field of view in orthographic projection

_"Field of view"_ is a term meaning _"how much of the world do you see at a given moment"_. The concept makes sense for both orthographic and perspective projections, but it is set using different properties in each case. For orthographic projection, this is determined by cgeref:TCastleOrthographic.Width[Viewport.Camera.Orthographic.Width] and cgeref:TCastleOrthographic.Height[Viewport.Camera.Orthographic.Height].

A viewport created using the _"Add User Interface -> Viewport (2D)"_ menu item has, by default,

- cgeref:TCastleOrthographic.Height[Viewport.Camera.Orthographic.Height] = `1000` and

- cgeref:TCastleOrthographic.Width[Viewport.Camera.Orthographic.Width] = `0`.

This means that, regardless of the window size, and even regardless of the _simulated_ (for UI scaling) window size, in your viewport you will always see exactly an object that has height (Y) equal to 1000. For example, if you add a cgeref:TCastleScene[], cgeref:TCastleImageTransform[] or cgeref:TCastlePlane[] with height (Y) equal to 1000, then their height will match perfectly the vertical field of view of the viewport. The horizontal field of view follows the aspect ratio of the viewport control.

There are other ways to control the field of view, see the cgeref:TCastleOrthographic.Width[Viewport.Camera.Orthographic.Width] and cgeref:TCastleOrthographic.Height[Viewport.Camera.Orthographic.Height] docs.

For example: You can set cgeref:TCastleOrthographic.Width[Viewport.Camera.Orthographic.Width] and cgeref:TCastleOrthographic.Height[Viewport.Camera.Orthographic.Height] to both be zero. In this case, the viewport control size (after UI scaling) determines this field of view. With the default UI scaling to 1600 x 900, this likely means that you will see an area 1600 x 900 in your viewport (it may be a bit taller or wider, if user resizes the window).

## Origin in orthographic projection

A viewport created using the _"Add User Interface -> Viewport (2D)"_ menu item has, by default, cgeref:TCastleOrthographic.Origin[Viewport.Camera.Orthographic.Origin] set as `(0.5,0.5)`. This means that the camera position determines what is visible in the _middle_ of the viewport. In effect, when `Camera.Translation` is `(0, 0, 0)`, the _middle_ of the viewport will show the things at position `(0, 0, 0)` in your world. This is most comfortable if you place your assets around the `(0, 0, 0)` point.

As an example, you can add a `TCastleScene` with an image or a sprite sheet. By default their pivot is in the middle of the asset. So if cgeref:TCastleOrthographic.Origin[Viewport.Camera.Orthographic.Origin] is `(0.5,0.5)` you will see them in the middle of the viewport.

You can change cgeref:TCastleOrthographic.Origin[Viewport.Camera.Orthographic.Origin] to whatever makes sense for your game. For example, cgeref:TCastleOrthographic.Origin[Viewport.Camera.Orthographic.Origin] equal to `(0, 0)` means that the camera position determines what is visible at the _left-bottom viewport corner_. So when camera position is `(0, 0, 0)` the left-bottom viewport corner will show the things at position `(0, 0, 0)` in your world.

## 2D assets

Simply add cgeref:TCastleScene[] instances to your 2D world, just like you would in 3D.

You can use any link:creating_data_model_formats.php[supported model format].

* You can use link:sprite_sheets[sprite sheets].
* You can use link:using_images[images].
* You can use link:spine[Spine] with smooth skeletal 2D animations.
* It is perfectly reasonable to use link:gltf[glTF] (e.g. exported from link:blender[Blender]) to do 2D art as well.
* Primitives like cgeref:TCastleText[] and cgeref:TCastlePlane[] (make sure to set axis to 2, meaning _"Z"_)  are also useful in 2D.

## Blending

Blending (partial transparency) should work in 2D games automatically.

Shapes using blending will be sorted following cgeref:TCastleViewport.BlendingSort[] rules. This is by default cgeref:sortAuto[], which means it detects typical 2D camera setup and then behaves like cgeref:sort2D[].

See link:blending[blending] for more details about blending, and see link:manual_alpha_bleeding.php[alpha bleeding] for details about how to prepare your images to behave correctly with blending.

## Advanced: Turning any viewport (like 3D) into 2D

There is really no strict distinction between 3D and 2D viewports in _Castle Game Engine_. In both cases you have `TCastleViewport`, just some sensible defaults are different. In _"Viewport (2D)"_ the camera projection is _orthographic_ and design-time navigation method is 2D.

You can always turn a "regular" viewport (with defaults for 3D) into 2D.

- Use the _"Viewport -> 2D Camera And Projection At Runtime"_. See the cgeref:TCastleViewport.Setup2D[] method reference for details what it does. You can also manually change cgeref:TCastleCamera.ProjectionType[Viewport.Camera.ProjectionType] and adjust other cgeref:TCastleCamera.Orthographic[Viewport.Camera.Orthographic] properties.
- Use the _"Viewport -> Toggle Perspective / Orthogonal"_ to change design-time camera to _orthographic_
- Use the _"Viewport -> Front"_  and then zoom out with mouse wheel to view a useful piece of 2D world
- Use the _"Viewport -> 2D"_ to activate 2D-specific navigation

You can also just place 2D (flat) items in a 3D viewport. It is really your choice

- whether you use flat or not objects,

- whether you use orthographic or perspective projection,

- what design-time navigation you use (2D, Fly...) etc.

And all these choices are in fact independent of each other. You can mix 2D and 3D stuff freely in CGE.

////
TODO: tutorial
  Add scene.
  We could use Camera -> View All...
    but instead we will move things.
  Add some navigation, position camera, save navigatio by "Initial := Current".
  Run.
////
