# Scene Graph: X3D nodes
include::common.adoc[]

cgeimg::float[
  sunny_street_tree_hard.png|Close up shadows on the tree,
  water_reflections.png|Water reflections by optimized GeneratedCubeMapTexture,
  rendered_texture_mirror_2.png|Mirrors by RenderedTexture by Victor Amat
]

== Introduction: What is X3D?

X3D is an open standard that defines:

1. A set of *nodes* that describe 3D and 2D content, like shapes (meshes, boxes, spheres), materials, lights, cameras, animations, interactions, shaders, sounds, cube maps (mirrors)...
+
These nodes are the important building block of our _Castle Game Engine_. You can load and display them using cgeref:TCastleScene[].
+
In our engine, in addition to the standard X3D nodes, we also define a few _extension nodes_. E.g. we add nodes to make link:compositing_shaders.php[shader effects], link:x3d_extensions_screen_effects.php[screen (post-processing) effects], shadows and more.

2. A *file format* to load and save these nodes in files.
+
There are multiple _encodings_ of X3D nodes, we support the two most common: _XML encoding_ and _classic encoding_. Both these encodings are just text files -- you don't need any special software to edit them, any text editor will do just fine.
+
Various 3D modeling applications can export to it. Unfortunately, current link:blender[Blender] exporter to X3D lacks a lot of important features (animations, PBR materials, any textures, metadata...) so we don't recommend using it.
+
As a file format, we recommend using link:gltf[glTF] instead.

In our engine, the first point is the most important: *X3D nodes are the core building block of everything*. That is, everything you see loaded into cgeref:TCastleScene[] is a graph of X3D nodes. All link:creating_data_model_formats.php[3D and 2D model formats] are loaded into a graph of X3D nodes. You have Pascal API available to manipulate these nodes, to create and modify them at runtime.

== Examples

See our link:demo_models.php[demo models] for example X3D models.

You can load and display any X3D model using:

- Our link:castle-model-viewer[Castle Model Viewer].

- Any other _Castle Game Engine_ tool. The engine even features a ready _"3D Model Viewer"_ project template and we encourage you to use it to create your own custom viewer.

- A number of other X3D viewers and tools are available (including free and open-source). To name a few:
+
--
- https://freewrl.sourceforge.io/[FreeWRL]
- https://create3000.github.io/x_ite/[X_ITE]
- https://www.x3dom.org/[X3DOM]
- https://www.web3d.org/x3d/content/examples/X3dResources.html[Many more tools are collected here].
--

== Learning X3D

- link:x3d_implementation_status.php[Supported nodes are documented here].
//The nodes are divided into sections (X3D specification calls these _"components"_, not to be confused with Pascal components) where they are defined.

- http://www.web3d.org/standards[The X3D specifications] are your ultimate resource to learn X3D. You will most likely want to browse link:https://www.web3d.org/documents/specifications/19775-1/V4.0/Part01/Architecture.html[X3D Architecture and base components specification], which describes the available X3D _nodes_.
//The nodes are grouped into _components_.

== X3D in Pascal

X3D nodes are the _scene graph_ of our engine. Once you load a 3D or 2D model into cgeref:TCastleScene[] (whether it was in X3D format or anything else, like link:gltf[glTF]), you have a graph of X3D nodes. The root of this graph is available as cgeref:TCastleSceneCore.RootNode[].

Every X3D node corresponds to a Pascal class with appropriate fields, and you can freely link:viewport_and_scenes_from_code#_building_a_mesh_using_code[create and modify X3D nodes at runtime].

For example, consider an X3D node
link:https://www.web3d.org/documents/specifications/19775-1/V4.0/Part01/components/geometry3D.html#Box[Box].
This node in X3D has fields:

- `size` (the X3D type is `SFVec3f`)
- `solid` (the X3D type is `SFBool`).

In Pascal, this node corresponds to the class cgeref:TBoxNode[], with properties

- cgeref:TBoxNode.Size[Size: TVector3]
- cgeref:TAbstractGeometryNode.Solid[Solid: Boolean].

You can create and edit instances of cgeref:TBoxNode[] and use cgeref:TCastleScene[] to render them.

See for example:

- link:viewport_and_scenes_from_code#_building_a_mesh_using_code[Pascal example how to create a mesh],
- link:x3d_implementation_geometry3d.php[Another Pascal example of creating a 3D mesh (TIndexedFaceSetNode)] is here,
- link:x3d_implementation_geometry2d.php[Pascal example of setting up 2D rectangle and lines].

You can also https://forum.castle-engine.io/t/creating-objects-on-the-fly/140/[pre-process the loaded scene (e.g. change the texture), by changing the X3D nodes graph (see this forum post for details)].

=== X3D node instance lifetime in Pascal

The X3D nodes have a reference-counting mechanism. The node (cgeref:TX3DNode[] or any descendant) is freed when the reference count of it changes from non-zero to zero.

So in the usual case, if you set the node as a value of some property of the other node, then you no longer need to think about releasing this node -- it will be released along with the parent. For example:

[source,pascal]
----
var
  Geometry: TBoxNode;
  Shape: TShapeNode;
  Root: TX3DRootNode;
begin
  Geometry := TBoxNode.Create;

  Shape := TShapeNode.Create;
  Shape.Geometry := Geometry;

  { Now you no longer need to worry about freeing Geometry.
    It will be freed along with Shape.
    Note that there's a shortcut for above 3 lines:

    Geometry := TBoxNode.CreateWithShape(Shape);
  }

  Root := TX3DRootNode.Create;
  Root.AddChildren(Shape);

  { Now you no longer need to worry about freeing Shape.
    It will be freed along with Root. }

  // to be continued ...
----

Moreover, when you load nodes into cgeref:TCastleScene[] using cgeref:TCastleSceneCore.Load[Scene.Load(MyNodes, true)] -- the 2nd parameter equal `true` means that `Scene` takes ownership of the whole nodes tree. So the whole cgeref:TX3DRootNode[] instance will be freed along with `Scene`.

So we can continue the example above:

[source,pascal]
----
  Scene := TCastleScene.Create(Application);
  Scene.Load(Root, true);

  { Now you no longer need to worry about freeing Root.
    It will be freed along with Scene. }
----

And `Scene` is a regular Pascal `TComponent`, with usual component ownership. In the above example, it is owned by the `Application` singleton. In larger application, when using link:views[], it will often be owned by cgeref:TCastleView.FreeAtStop[]. And you can always free the scene explicitly too, like `FreeAndNil(Scene);`.

Notes:


- If a node is not referenced from anywhere, you are responsible for freeing it manually as usual. For example, if we would not load `Root` into `Scene` (if we remove the line `Scene.Load(Root, true)` from above example) then at some point you should call `FreeAndNil(Root);`.

- If for some reason you do not want the node to be automatically freed, you can use cgeref:TX3DNode.KeepExistingBegin[] and cgeref:TX3DNode.KeepExistingEnd[].
