<?php /* Version numbers automatically generated by generate_versions.sh */
  define('VERSION_CASTLE', '0.9.4');
  define('VERSION_LETS_TAKE_A_WALK', '1.2.4');
  define('VERSION_MALFUNCTION', '1.2.7');
  define('VERSION_KAMBI_LINES', '1.1.6');
  define('VERSION_VIEW3DSCENE', '3.11.0');
  define('VERSION_RAYHUNTER', '1.3.3');
  define('VERSION_GLVIEWIMAGE', '1.4.0');
  define('VERSION_GLPLOTTER', '1.2.4');
  define('VERSION_BEZIER_CURVES', '1.1.8');
  define('VERSION_GLINFORMATION', '1.2.1');
  define('VERSION_GLINFORMATION_GLUT', '1.2.1');
  define('VERSION_GEN_FUNCTION', '1.0.4');
  define('VERSION_CASTLE_GAME_ENGINE', '3.0.0');
  define('VERSION_DEMO_MODELS', '3.1.0');
?>
