<?php
  /* Version numbers automatically generated by generate_versions.sh
     on 2007-09-01 */
  define('VERSION_CASTLE', '0.7.0');
  define('VERSION_LETS_TAKE_A_WALK', '1.2.0');
  define('VERSION_MALFUNCTION', '1.2.3');
  define('VERSION_KAMBI_LINES', '1.1.2');
  define('VERSION_VIEW3DSCENE', '2.2.0');
  define('VERSION_RAYHUNTER', '1.2.1');
  define('VERSION_GLVIEWIMAGE', '1.2.1');
  define('VERSION_GLPLOTTER', '1.1.6');
  define('VERSION_BEZIER_CURVES', '1.1.5');
  define('VERSION_GLCAPS', '1.1.1');
  define('VERSION_GLCAPS_GLUT', '1.1.1');
  define('VERSION_GEN_FUNCTION', '1.0.1');
  define('VERSION_KAMBI_VRML_GAME_ENGINE', '1.1.0');
  define('VERSION_KAMBI_VRML_TEST_SUITE', '1.1.0');
?>
