<?php
require_once 'castle_engine_functions.php';

castle_header("Reference generated by pasdoc", array(
  'path' => array('documentation')
));
?>

<?php echo pretty_heading('Reference'); ?>

<div style="text-align: center;">
<div style="font-weight: bold; font-size: large; border: thin outset black; background: #ffff91; display: inline-block; padding: 0.5em;">Go to <a href="apidoc/html/index.html">reference of Castle Game Engine API</a></div>
</div>

<p>You want to start reading from the initial
<i>"Introduction"</i> page of this reference. It describes how to compile
the engine, examples and such.</p>

<p>This reference was generated by
<a href="http://pasdoc.sourceforge.net/">PasDoc</a>.
If you have any questions, or suggestions,
please <?php echo a_href_page('let me know', 'forum'); ?>.
Michalis is both an author of this engine and a developer of
PasDoc, so everything can be fixed and improved :)</p>

<?php
  castle_footer();
?>
