<?php
  require_once 'vrmlengine_functions.php';

  vrmlengine_header("Reference generated by pasdoc");
?>

<div style="text-align: center;">
<div style="font-weight: bold; font-size: large; border: thin outset black; background: #ffff91; display: inline-block; padding: 0.5em;">Go to <a href="apidoc/html/index.html">reference of Kambi VRML game engine API</a></div>
</div>

<p>This is a reference of
<?php echo a_href_page('Kambi VRML game engine', 'kambi_vrml_game_engine'); ?>
 as generated by
<a href="http://pasdoc.sourceforge.net/">pasdoc</a>.<br/>
Other formats, like PDF, used to be available too, but they look too ugly
for now.</p>

<!--
  /* This style is copied from Media Wiki style for table of contents
     (/wiki/stylesheets/commonPrint.css) */
-->
<p><div style="border:1px solid #aaaaaa; background-color:#f9f9f9; padding:5px">
Sort of disclaimer: please note that for now
<ul>
  <li>some parts of the reference are still in Polish
  <li>generated reference for some units doesn't look good
    <!-- (sometimes
    I wrote one comment documenting couple of things at once,
    sometimes I wrote a list but in the past there was no markup
    in pasdoc to handle this etc.)
  <li>there are many comments in sources that were not converted
    by pasdoc because pasdoc couldn't associate them with any item
    -->
</ul>

I'm working on all these issues, by correcting my code
and by working on <a href="http://pasdoc.sourceforge.net/">pasdoc</a> itself.
Feel free to browse this reference and
send any comments to <?php echo MAILING_LIST_LINK; ?>.
I'm interested in all comments,
both as the author of this code and as a developer of
<a href="http://pasdoc.sourceforge.net/">pasdoc</a>.
</div>

<?php
  if (!IS_GEN_LOCAL) {
    $counter = php_counter("reference", TRUE);
  };

  vrmlengine_footer();
?>
