<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'jetpack-protect',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-admin-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-admin-ui',
      'ver' => '0.2.19',
    ),
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '1.17.34',
    ),
    'jetpack-config' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-config',
      'ver' => '1.15.1',
    ),
    'jetpack-connection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection',
      'ver' => '1.51.7',
    ),
    'jetpack-idc' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-identity-crisis',
      'ver' => '0.8.40',
    ),
    'jetpack-ip' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-ip',
      'ver' => '0.1.2',
    ),
    'jetpack-jitm' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-jitm',
      'ver' => '2.3.4',
    ),
    'jetpack-licensing' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-licensing',
      'ver' => '1.8.2',
    ),
    'jetpack-my-jetpack' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-my-jetpack',
      'ver' => '2.9.1',
    ),
    'jetpack-password-checker' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-password-checker',
      'ver' => '0.2.13',
    ),
    'jetpack-plugins-installer' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-plugins-installer',
      'ver' => '0.2.3',
    ),
    'jetpack-sync' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-sync',
      'ver' => '1.47.4',
    ),
    'jetpack-transport-helper' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-transport-helper',
      'ver' => '0.1.4',
    ),
    'jetpack-waf' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-waf',
      'ver' => '0.11.4',
    ),
  ),
);
