# -*- mode: shell-script -*-
#
# Dockerfile that defines the Docker image with view3dscene and tovrmlx3d.
# Used by "Convert everything to X3D" tool on
# https://castle-engine.io/convert.php .
#
# Build and upload by build.sh.

FROM debian:stable
COPY bin/* /usr/local/bin/
